version: "3.8"

networks:
  grafana-net:
    driver: bridge

volumes:
  prom_data:

services:
  grafana:
      container_name: "grafana"
      image: grafana/grafana:8.3.3
      environment:
        - 'GF_AUTH_ANONYMOUS_ENABLED=true'
        - 'GF_AUTH_ANONYMOUS_ORG_ROLE=Admin'
        - 'GF_AUTH_DISABLE_LOGIN_FORM=true'
      ports:
        - "3000:3000"
      networks:
        - grafana-net
      volumes:
        - prom_data:/etc/grafana
        - ./grafana.yml:/etc/grafana/provisioning/datasources/datasources.yml
  prom:
    container_name: "prometheus"
    image: prom/prometheus:v2.31.1
    hostname: localhost
    user: "0:0"
    ports:
      - "9090:9090"
    networks:
      - grafana-net
    volumes:
      - prom_data:/etc/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=15d"
      - "--web.enable-lifecycle"