#pragma once

#include <unordered_map>
#include <string>

#define FIX_VER_MAJOR 4
#define FIX_VER_MINOR 4

namespace fix_spec {
	enum tag: int {
		Account = 1,
		AdvId = 2,
		AdvRefID = 3,
		AdvSide = 4,
		AdvTransType = 5,
		AvgPx = 6,
		BeginSeqNo = 7,
		BeginString = 8,
		BodyLength = 9,
		CheckSum = 10,
		ClOrdID = 11,
		Commission = 12,
		CommType = 13,
		CumQty = 14,
		Currency = 15,
		EndSeqNo = 16,
		ExecID = 17,
		ExecInst = 18,
		ExecRefID = 19,
		HandlInst = 21,
		SecurityIDSource = 22,
		IOIID = 23,
		IOIQltyInd = 25,
		IOIRefID = 26,
		IOIQty = 27,
		IOITransType = 28,
		LastCapacity = 29,
		LastMkt = 30,
		LastPx = 31,
		LastQty = 32,
		LinesOfText = 33,
		MsgSeqNum = 34,
		MsgType = 35,
		NewSeqNo = 36,
		OrderID = 37,
		OrderQty = 38,
		OrdStatus = 39,
		OrdType = 40,
		OrigClOrdID = 41,
		OrigTime = 42,
		PossDupFlag = 43,
		Price = 44,
		RefSeqNum = 45,
		SecurityID = 48,
		SenderCompID = 49,
		SenderSubID = 50,
		SendingTime = 52,
		Quantity = 53,
		Side = 54,
		Symbol = 55,
		TargetCompID = 56,
		TargetSubID = 57,
		Text = 58,
		TimeInForce = 59,
		TransactTime = 60,
		Urgency = 61,
		ValidUntilTime = 62,
		SettlType = 63,
		SettlDate = 64,
		SymbolSfx = 65,
		ListID = 66,
		ListSeqNo = 67,
		TotNoOrders = 68,
		ListExecInst = 69,
		AllocID = 70,
		AllocTransType = 71,
		RefAllocID = 72,
		NoOrders = 73,
		AvgPxPrecision = 74,
		TradeDate = 75,
		PositionEffect = 77,
		NoAllocs = 78,
		AllocAccount = 79,
		AllocQty = 80,
		ProcessCode = 81,
		NoRpts = 82,
		RptSeq = 83,
		CxlQty = 84,
		NoDlvyInst = 85,
		AllocStatus = 87,
		AllocRejCode = 88,
		Signature = 89,
		SecureDataLen = 90,
		SecureData = 91,
		SignatureLength = 93,
		EmailType = 94,
		RawDataLength = 95,
		RawData = 96,
		PossResend = 97,
		EncryptMethod = 98,
		StopPx = 99,
		ExDestination = 100,
		CxlRejReason = 102,
		OrdRejReason = 103,
		IOIQualifier = 104,
		WaveNo = 105,
		Issuer = 106,
		SecurityDesc = 107,
		HeartBtInt = 108,
		MinQty = 110,
		MaxFloor = 111,
		TestReqID = 112,
		ReportToExch = 113,
		LocateReqd = 114,
		OnBehalfOfCompID = 115,
		OnBehalfOfSubID = 116,
		QuoteID = 117,
		NetMoney = 118,
		SettlCurrAmt = 119,
		SettlCurrency = 120,
		ForexReq = 121,
		OrigSendingTime = 122,
		GapFillFlag = 123,
		NoExecs = 124,
		ExpireTime = 126,
		DKReason = 127,
		DeliverToCompID = 128,
		DeliverToSubID = 129,
		IOINaturalFlag = 130,
		QuoteReqID = 131,
		BidPx = 132,
		OfferPx = 133,
		BidSize = 134,
		OfferSize = 135,
		NoMiscFees = 136,
		MiscFeeAmt = 137,
		MiscFeeCurr = 138,
		MiscFeeType = 139,
		PrevClosePx = 140,
		ResetSeqNumFlag = 141,
		SenderLocationID = 142,
		TargetLocationID = 143,
		OnBehalfOfLocationID = 144,
		DeliverToLocationID = 145,
		NoRelatedSym = 146,
		Subject = 147,
		Headline = 148,
		URLLink = 149,
		ExecType = 150,
		LeavesQty = 151,
		CashOrderQty = 152,
		AllocAvgPx = 153,
		AllocNetMoney = 154,
		SettlCurrFxRate = 155,
		SettlCurrFxRateCalc = 156,
		NumDaysInterest = 157,
		AccruedInterestRate = 158,
		AccruedInterestAmt = 159,
		SettlInstMode = 160,
		AllocText = 161,
		SettlInstID = 162,
		SettlInstTransType = 163,
		EmailThreadID = 164,
		SettlInstSource = 165,
		SecurityType = 167,
		EffectiveTime = 168,
		StandInstDbType = 169,
		StandInstDbName = 170,
		StandInstDbID = 171,
		SettlDeliveryType = 172,
		BidSpotRate = 188,
		BidForwardPoints = 189,
		OfferSpotRate = 190,
		OfferForwardPoints = 191,
		OrderQty2 = 192,
		SettlDate2 = 193,
		LastSpotRate = 194,
		LastForwardPoints = 195,
		AllocLinkID = 196,
		AllocLinkType = 197,
		SecondaryOrderID = 198,
		NoIOIQualifiers = 199,
		MaturityMonthYear = 200,
		PutOrCall = 201,
		StrikePrice = 202,
		CoveredOrUncovered = 203,
		OptAttribute = 206,
		SecurityExchange = 207,
		NotifyBrokerOfCredit = 208,
		AllocHandlInst = 209,
		MaxShow = 210,
		PegOffsetValue = 211,
		XmlDataLen = 212,
		XmlData = 213,
		SettlInstRefID = 214,
		NoRoutingIDs = 215,
		RoutingType = 216,
		RoutingID = 217,
		Spread = 218,
		BenchmarkCurveCurrency = 220,
		BenchmarkCurveName = 221,
		BenchmarkCurvePoint = 222,
		CouponRate = 223,
		CouponPaymentDate = 224,
		IssueDate = 225,
		RepurchaseTerm = 226,
		RepurchaseRate = 227,
		Factor = 228,
		TradeOriginationDate = 229,
		ExDate = 230,
		ContractMultiplier = 231,
		NoStipulations = 232,
		StipulationType = 233,
		StipulationValue = 234,
		YieldType = 235,
		Yield = 236,
		TotalTakedown = 237,
		Concession = 238,
		RepoCollateralSecurityType = 239,
		RedemptionDate = 240,
		UnderlyingCouponPaymentDate = 241,
		UnderlyingIssueDate = 242,
		UnderlyingRepoCollateralSecurityType = 243,
		UnderlyingRepurchaseTerm = 244,
		UnderlyingRepurchaseRate = 245,
		UnderlyingFactor = 246,
		UnderlyingRedemptionDate = 247,
		LegCouponPaymentDate = 248,
		LegIssueDate = 249,
		LegRepoCollateralSecurityType = 250,
		LegRepurchaseTerm = 251,
		LegRepurchaseRate = 252,
		LegFactor = 253,
		LegRedemptionDate = 254,
		CreditRating = 255,
		UnderlyingCreditRating = 256,
		LegCreditRating = 257,
		TradedFlatSwitch = 258,
		BasisFeatureDate = 259,
		BasisFeaturePrice = 260,
		MDReqID = 262,
		SubscriptionRequestType = 263,
		MarketDepth = 264,
		MDUpdateType = 265,
		AggregatedBook = 266,
		NoMDEntryTypes = 267,
		NoMDEntries = 268,
		MDEntryType = 269,
		MDEntryPx = 270,
		MDEntrySize = 271,
		MDEntryDate = 272,
		MDEntryTime = 273,
		TickDirection = 274,
		MDMkt = 275,
		QuoteCondition = 276,
		TradeCondition = 277,
		MDEntryID = 278,
		MDUpdateAction = 279,
		MDEntryRefID = 280,
		MDReqRejReason = 281,
		MDEntryOriginator = 282,
		LocationID = 283,
		DeskID = 284,
		DeleteReason = 285,
		OpenCloseSettlFlag = 286,
		SellerDays = 287,
		MDEntryBuyer = 288,
		MDEntrySeller = 289,
		MDEntryPositionNo = 290,
		FinancialStatus = 291,
		CorporateAction = 292,
		DefBidSize = 293,
		DefOfferSize = 294,
		NoQuoteEntries = 295,
		NoQuoteSets = 296,
		QuoteStatus = 297,
		QuoteCancelType = 298,
		QuoteEntryID = 299,
		QuoteRejectReason = 300,
		QuoteResponseLevel = 301,
		QuoteSetID = 302,
		QuoteRequestType = 303,
		TotNoQuoteEntries = 304,
		UnderlyingSecurityIDSource = 305,
		UnderlyingIssuer = 306,
		UnderlyingSecurityDesc = 307,
		UnderlyingSecurityExchange = 308,
		UnderlyingSecurityID = 309,
		UnderlyingSecurityType = 310,
		UnderlyingSymbol = 311,
		UnderlyingSymbolSfx = 312,
		UnderlyingMaturityMonthYear = 313,
		UnderlyingPutOrCall = 315,
		UnderlyingStrikePrice = 316,
		UnderlyingOptAttribute = 317,
		UnderlyingCurrency = 318,
		SecurityReqID = 320,
		SecurityRequestType = 321,
		SecurityResponseID = 322,
		SecurityResponseType = 323,
		SecurityStatusReqID = 324,
		UnsolicitedIndicator = 325,
		SecurityTradingStatus = 326,
		HaltReason = 327,
		InViewOfCommon = 328,
		DueToRelated = 329,
		BuyVolume = 330,
		SellVolume = 331,
		HighPx = 332,
		LowPx = 333,
		Adjustment = 334,
		TradSesReqID = 335,
		TradingSessionID = 336,
		ContraTrader = 337,
		TradSesMethod = 338,
		TradSesMode = 339,
		TradSesStatus = 340,
		TradSesStartTime = 341,
		TradSesOpenTime = 342,
		TradSesPreCloseTime = 343,
		TradSesCloseTime = 344,
		TradSesEndTime = 345,
		NumberOfOrders = 346,
		MessageEncoding = 347,
		EncodedIssuerLen = 348,
		EncodedIssuer = 349,
		EncodedSecurityDescLen = 350,
		EncodedSecurityDesc = 351,
		EncodedListExecInstLen = 352,
		EncodedListExecInst = 353,
		EncodedTextLen = 354,
		EncodedText = 355,
		EncodedSubjectLen = 356,
		EncodedSubject = 357,
		EncodedHeadlineLen = 358,
		EncodedHeadline = 359,
		EncodedAllocTextLen = 360,
		EncodedAllocText = 361,
		EncodedUnderlyingIssuerLen = 362,
		EncodedUnderlyingIssuer = 363,
		EncodedUnderlyingSecurityDescLen = 364,
		EncodedUnderlyingSecurityDesc = 365,
		AllocPrice = 366,
		QuoteSetValidUntilTime = 367,
		QuoteEntryRejectReason = 368,
		LastMsgSeqNumProcessed = 369,
		RefTagID = 371,
		RefMsgType = 372,
		SessionRejectReason = 373,
		BidRequestTransType = 374,
		ContraBroker = 375,
		ComplianceID = 376,
		SolicitedFlag = 377,
		ExecRestatementReason = 378,
		BusinessRejectRefID = 379,
		BusinessRejectReason = 380,
		GrossTradeAmt = 381,
		NoContraBrokers = 382,
		MaxMessageSize = 383,
		NoMsgTypes = 384,
		MsgDirection = 385,
		NoTradingSessions = 386,
		TotalVolumeTraded = 387,
		DiscretionInst = 388,
		DiscretionOffsetValue = 389,
		BidID = 390,
		ClientBidID = 391,
		ListName = 392,
		TotNoRelatedSym = 393,
		BidType = 394,
		NumTickets = 395,
		SideValue1 = 396,
		SideValue2 = 397,
		NoBidDescriptors = 398,
		BidDescriptorType = 399,
		BidDescriptor = 400,
		SideValueInd = 401,
		LiquidityPctLow = 402,
		LiquidityPctHigh = 403,
		LiquidityValue = 404,
		EFPTrackingError = 405,
		FairValue = 406,
		OutsideIndexPct = 407,
		ValueOfFutures = 408,
		LiquidityIndType = 409,
		WtAverageLiquidity = 410,
		ExchangeForPhysical = 411,
		OutMainCntryUIndex = 412,
		CrossPercent = 413,
		ProgRptReqs = 414,
		ProgPeriodInterval = 415,
		IncTaxInd = 416,
		NumBidders = 417,
		BidTradeType = 418,
		BasisPxType = 419,
		NoBidComponents = 420,
		Country = 421,
		TotNoStrikes = 422,
		PriceType = 423,
		DayOrderQty = 424,
		DayCumQty = 425,
		DayAvgPx = 426,
		GTBookingInst = 427,
		NoStrikes = 428,
		ListStatusType = 429,
		NetGrossInd = 430,
		ListOrderStatus = 431,
		ExpireDate = 432,
		ListExecInstType = 433,
		CxlRejResponseTo = 434,
		UnderlyingCouponRate = 435,
		UnderlyingContractMultiplier = 436,
		ContraTradeQty = 437,
		ContraTradeTime = 438,
		LiquidityNumSecurities = 441,
		MultiLegReportingType = 442,
		StrikeTime = 443,
		ListStatusText = 444,
		EncodedListStatusTextLen = 445,
		EncodedListStatusText = 446,
		PartyIDSource = 447,
		PartyID = 448,
		NetChgPrevDay = 451,
		PartyRole = 452,
		NoPartyIDs = 453,
		NoSecurityAltID = 454,
		SecurityAltID = 455,
		SecurityAltIDSource = 456,
		NoUnderlyingSecurityAltID = 457,
		UnderlyingSecurityAltID = 458,
		UnderlyingSecurityAltIDSource = 459,
		Product = 460,
		CFICode = 461,
		UnderlyingProduct = 462,
		UnderlyingCFICode = 463,
		TestMessageIndicator = 464,
		QuantityType = 465,
		BookingRefID = 466,
		IndividualAllocID = 467,
		RoundingDirection = 468,
		RoundingModulus = 469,
		CountryOfIssue = 470,
		StateOrProvinceOfIssue = 471,
		LocaleOfIssue = 472,
		NoRegistDtls = 473,
		MailingDtls = 474,
		InvestorCountryOfResidence = 475,
		PaymentRef = 476,
		DistribPaymentMethod = 477,
		CashDistribCurr = 478,
		CommCurrency = 479,
		CancellationRights = 480,
		MoneyLaunderingStatus = 481,
		MailingInst = 482,
		TransBkdTime = 483,
		ExecPriceType = 484,
		ExecPriceAdjustment = 485,
		DateOfBirth = 486,
		TradeReportTransType = 487,
		CardHolderName = 488,
		CardNumber = 489,
		CardExpDate = 490,
		CardIssNum = 491,
		PaymentMethod = 492,
		RegistAcctType = 493,
		Designation = 494,
		TaxAdvantageType = 495,
		RegistRejReasonText = 496,
		FundRenewWaiv = 497,
		CashDistribAgentName = 498,
		CashDistribAgentCode = 499,
		CashDistribAgentAcctNumber = 500,
		CashDistribPayRef = 501,
		CashDistribAgentAcctName = 502,
		CardStartDate = 503,
		PaymentDate = 504,
		PaymentRemitterID = 505,
		RegistStatus = 506,
		RegistRejReasonCode = 507,
		RegistRefID = 508,
		RegistDtls = 509,
		NoDistribInsts = 510,
		RegistEmail = 511,
		DistribPercentage = 512,
		RegistID = 513,
		RegistTransType = 514,
		ExecValuationPoint = 515,
		OrderPercent = 516,
		OwnershipType = 517,
		NoContAmts = 518,
		ContAmtType = 519,
		ContAmtValue = 520,
		ContAmtCurr = 521,
		OwnerType = 522,
		PartySubID = 523,
		NestedPartyID = 524,
		NestedPartyIDSource = 525,
		SecondaryClOrdID = 526,
		SecondaryExecID = 527,
		OrderCapacity = 528,
		OrderRestrictions = 529,
		MassCancelRequestType = 530,
		MassCancelResponse = 531,
		MassCancelRejectReason = 532,
		TotalAffectedOrders = 533,
		NoAffectedOrders = 534,
		AffectedOrderID = 535,
		AffectedSecondaryOrderID = 536,
		QuoteType = 537,
		NestedPartyRole = 538,
		NoNestedPartyIDs = 539,
		TotalAccruedInterestAmt = 540,
		MaturityDate = 541,
		UnderlyingMaturityDate = 542,
		InstrRegistry = 543,
		CashMargin = 544,
		NestedPartySubID = 545,
		Scope = 546,
		MDImplicitDelete = 547,
		CrossID = 548,
		CrossType = 549,
		CrossPrioritization = 550,
		OrigCrossID = 551,
		NoSides = 552,
		Username = 553,
		Password = 554,
		NoLegs = 555,
		LegCurrency = 556,
		TotNoSecurityTypes = 557,
		NoSecurityTypes = 558,
		SecurityListRequestType = 559,
		SecurityRequestResult = 560,
		RoundLot = 561,
		MinTradeVol = 562,
		MultiLegRptTypeReq = 563,
		LegPositionEffect = 564,
		LegCoveredOrUncovered = 565,
		LegPrice = 566,
		TradSesStatusRejReason = 567,
		TradeRequestID = 568,
		TradeRequestType = 569,
		PreviouslyReported = 570,
		TradeReportID = 571,
		TradeReportRefID = 572,
		MatchStatus = 573,
		MatchType = 574,
		OddLot = 575,
		NoClearingInstructions = 576,
		ClearingInstruction = 577,
		TradeInputSource = 578,
		TradeInputDevice = 579,
		NoDates = 580,
		AccountType = 581,
		CustOrderCapacity = 582,
		ClOrdLinkID = 583,
		MassStatusReqID = 584,
		MassStatusReqType = 585,
		OrigOrdModTime = 586,
		LegSettlType = 587,
		LegSettlDate = 588,
		DayBookingInst = 589,
		BookingUnit = 590,
		PreallocMethod = 591,
		UnderlyingCountryOfIssue = 592,
		UnderlyingStateOrProvinceOfIssue = 593,
		UnderlyingLocaleOfIssue = 594,
		UnderlyingInstrRegistry = 595,
		LegCountryOfIssue = 596,
		LegStateOrProvinceOfIssue = 597,
		LegLocaleOfIssue = 598,
		LegInstrRegistry = 599,
		LegSymbol = 600,
		LegSymbolSfx = 601,
		LegSecurityID = 602,
		LegSecurityIDSource = 603,
		NoLegSecurityAltID = 604,
		LegSecurityAltID = 605,
		LegSecurityAltIDSource = 606,
		LegProduct = 607,
		LegCFICode = 608,
		LegSecurityType = 609,
		LegMaturityMonthYear = 610,
		LegMaturityDate = 611,
		LegStrikePrice = 612,
		LegOptAttribute = 613,
		LegContractMultiplier = 614,
		LegCouponRate = 615,
		LegSecurityExchange = 616,
		LegIssuer = 617,
		EncodedLegIssuerLen = 618,
		EncodedLegIssuer = 619,
		LegSecurityDesc = 620,
		EncodedLegSecurityDescLen = 621,
		EncodedLegSecurityDesc = 622,
		LegRatioQty = 623,
		LegSide = 624,
		TradingSessionSubID = 625,
		AllocType = 626,
		NoHops = 627,
		HopCompID = 628,
		HopSendingTime = 629,
		HopRefID = 630,
		MidPx = 631,
		BidYield = 632,
		MidYield = 633,
		OfferYield = 634,
		ClearingFeeIndicator = 635,
		WorkingIndicator = 636,
		LegLastPx = 637,
		PriorityIndicator = 638,
		PriceImprovement = 639,
		Price2 = 640,
		LastForwardPoints2 = 641,
		BidForwardPoints2 = 642,
		OfferForwardPoints2 = 643,
		RFQReqID = 644,
		MktBidPx = 645,
		MktOfferPx = 646,
		MinBidSize = 647,
		MinOfferSize = 648,
		QuoteStatusReqID = 649,
		LegalConfirm = 650,
		UnderlyingLastPx = 651,
		UnderlyingLastQty = 652,
		LegRefID = 654,
		ContraLegRefID = 655,
		SettlCurrBidFxRate = 656,
		SettlCurrOfferFxRate = 657,
		QuoteRequestRejectReason = 658,
		SideComplianceID = 659,
		AcctIDSource = 660,
		AllocAcctIDSource = 661,
		BenchmarkPrice = 662,
		BenchmarkPriceType = 663,
		ConfirmID = 664,
		ConfirmStatus = 665,
		ConfirmTransType = 666,
		ContractSettlMonth = 667,
		DeliveryForm = 668,
		LastParPx = 669,
		NoLegAllocs = 670,
		LegAllocAccount = 671,
		LegIndividualAllocID = 672,
		LegAllocQty = 673,
		LegAllocAcctIDSource = 674,
		LegSettlCurrency = 675,
		LegBenchmarkCurveCurrency = 676,
		LegBenchmarkCurveName = 677,
		LegBenchmarkCurvePoint = 678,
		LegBenchmarkPrice = 679,
		LegBenchmarkPriceType = 680,
		LegBidPx = 681,
		LegIOIQty = 682,
		NoLegStipulations = 683,
		LegOfferPx = 684,
		LegOrderQty = 685,
		LegPriceType = 686,
		LegQty = 687,
		LegStipulationType = 688,
		LegStipulationValue = 689,
		LegSwapType = 690,
		Pool = 691,
		QuotePriceType = 692,
		QuoteRespID = 693,
		QuoteRespType = 694,
		QuoteQualifier = 695,
		YieldRedemptionDate = 696,
		YieldRedemptionPrice = 697,
		YieldRedemptionPriceType = 698,
		BenchmarkSecurityID = 699,
		ReversalIndicator = 700,
		YieldCalcDate = 701,
		NoPositions = 702,
		PosType = 703,
		LongQty = 704,
		ShortQty = 705,
		PosQtyStatus = 706,
		PosAmtType = 707,
		PosAmt = 708,
		PosTransType = 709,
		PosReqID = 710,
		NoUnderlyings = 711,
		PosMaintAction = 712,
		OrigPosReqRefID = 713,
		PosMaintRptRefID = 714,
		ClearingBusinessDate = 715,
		SettlSessID = 716,
		SettlSessSubID = 717,
		AdjustmentType = 718,
		ContraryInstructionIndicator = 719,
		PriorSpreadIndicator = 720,
		PosMaintRptID = 721,
		PosMaintStatus = 722,
		PosMaintResult = 723,
		PosReqType = 724,
		ResponseTransportType = 725,
		ResponseDestination = 726,
		TotalNumPosReports = 727,
		PosReqResult = 728,
		PosReqStatus = 729,
		SettlPrice = 730,
		SettlPriceType = 731,
		UnderlyingSettlPrice = 732,
		UnderlyingSettlPriceType = 733,
		PriorSettlPrice = 734,
		NoQuoteQualifiers = 735,
		AllocSettlCurrency = 736,
		AllocSettlCurrAmt = 737,
		InterestAtMaturity = 738,
		LegDatedDate = 739,
		LegPool = 740,
		AllocInterestAtMaturity = 741,
		AllocAccruedInterestAmt = 742,
		DeliveryDate = 743,
		AssignmentMethod = 744,
		AssignmentUnit = 745,
		OpenInterest = 746,
		ExerciseMethod = 747,
		TotNumTradeReports = 748,
		TradeRequestResult = 749,
		TradeRequestStatus = 750,
		TradeReportRejectReason = 751,
		SideMultiLegReportingType = 752,
		NoPosAmt = 753,
		AutoAcceptIndicator = 754,
		AllocReportID = 755,
		NoNested2PartyIDs = 756,
		Nested2PartyID = 757,
		Nested2PartyIDSource = 758,
		Nested2PartyRole = 759,
		Nested2PartySubID = 760,
		BenchmarkSecurityIDSource = 761,
		SecuritySubType = 762,
		UnderlyingSecuritySubType = 763,
		LegSecuritySubType = 764,
		AllowableOneSidednessPct = 765,
		AllowableOneSidednessValue = 766,
		AllowableOneSidednessCurr = 767,
		NoTrdRegTimestamps = 768,
		TrdRegTimestamp = 769,
		TrdRegTimestampType = 770,
		TrdRegTimestampOrigin = 771,
		ConfirmRefID = 772,
		ConfirmType = 773,
		ConfirmRejReason = 774,
		BookingType = 775,
		IndividualAllocRejCode = 776,
		SettlInstMsgID = 777,
		NoSettlInst = 778,
		LastUpdateTime = 779,
		AllocSettlInstType = 780,
		NoSettlPartyIDs = 781,
		SettlPartyID = 782,
		SettlPartyIDSource = 783,
		SettlPartyRole = 784,
		SettlPartySubID = 785,
		SettlPartySubIDType = 786,
		DlvyInstType = 787,
		TerminationType = 788,
		NextExpectedMsgSeqNum = 789,
		OrdStatusReqID = 790,
		SettlInstReqID = 791,
		SettlInstReqRejCode = 792,
		SecondaryAllocID = 793,
		AllocReportType = 794,
		AllocReportRefID = 795,
		AllocCancReplaceReason = 796,
		CopyMsgIndicator = 797,
		AllocAccountType = 798,
		OrderAvgPx = 799,
		OrderBookingQty = 800,
		NoSettlPartySubIDs = 801,
		NoPartySubIDs = 802,
		PartySubIDType = 803,
		NoNestedPartySubIDs = 804,
		NestedPartySubIDType = 805,
		NoNested2PartySubIDs = 806,
		Nested2PartySubIDType = 807,
		AllocIntermedReqType = 808,
		UnderlyingPx = 810,
		PriceDelta = 811,
		ApplQueueMax = 812,
		ApplQueueDepth = 813,
		ApplQueueResolution = 814,
		ApplQueueAction = 815,
		NoAltMDSource = 816,
		AltMDSourceID = 817,
		SecondaryTradeReportID = 818,
		AvgPxIndicator = 819,
		TradeLinkID = 820,
		OrderInputDevice = 821,
		UnderlyingTradingSessionID = 822,
		UnderlyingTradingSessionSubID = 823,
		TradeLegRefID = 824,
		ExchangeRule = 825,
		TradeAllocIndicator = 826,
		ExpirationCycle = 827,
		TrdType = 828,
		TrdSubType = 829,
		TransferReason = 830,
		AsgnReqID = 831,
		TotNumAssignmentReports = 832,
		AsgnRptID = 833,
		ThresholdAmount = 834,
		PegMoveType = 835,
		PegOffsetType = 836,
		PegLimitType = 837,
		PegRoundDirection = 838,
		PeggedPrice = 839,
		PegScope = 840,
		DiscretionMoveType = 841,
		DiscretionOffsetType = 842,
		DiscretionLimitType = 843,
		DiscretionRoundDirection = 844,
		DiscretionPrice = 845,
		DiscretionScope = 846,
		TargetStrategy = 847,
		TargetStrategyParameters = 848,
		ParticipationRate = 849,
		TargetStrategyPerformance = 850,
		LastLiquidityInd = 851,
		PublishTrdIndicator = 852,
		ShortSaleReason = 853,
		QtyType = 854,
		SecondaryTrdType = 855,
		TradeReportType = 856,
		AllocNoOrdersType = 857,
		SharedCommission = 858,
		ConfirmReqID = 859,
		AvgParPx = 860,
		ReportedPx = 861,
		NoCapacities = 862,
		OrderCapacityQty = 863,
		NoEvents = 864,
		EventType = 865,
		EventDate = 866,
		EventPx = 867,
		EventText = 868,
		PctAtRisk = 869,
		NoInstrAttrib = 870,
		InstrAttribType = 871,
		InstrAttribValue = 872,
		DatedDate = 873,
		InterestAccrualDate = 874,
		CPProgram = 875,
		CPRegType = 876,
		UnderlyingCPProgram = 877,
		UnderlyingCPRegType = 878,
		UnderlyingQty = 879,
		TrdMatchID = 880,
		SecondaryTradeReportRefID = 881,
		UnderlyingDirtyPrice = 882,
		UnderlyingEndPrice = 883,
		UnderlyingStartValue = 884,
		UnderlyingCurrentValue = 885,
		UnderlyingEndValue = 886,
		NoUnderlyingStips = 887,
		UnderlyingStipType = 888,
		UnderlyingStipValue = 889,
		MaturityNetMoney = 890,
		MiscFeeBasis = 891,
		TotNoAllocs = 892,
		LastFragment = 893,
		CollReqID = 894,
		CollAsgnReason = 895,
		CollInquiryQualifier = 896,
		NoTrades = 897,
		MarginRatio = 898,
		MarginExcess = 899,
		TotalNetValue = 900,
		CashOutstanding = 901,
		CollAsgnID = 902,
		CollAsgnTransType = 903,
		CollRespID = 904,
		CollAsgnRespType = 905,
		CollAsgnRejectReason = 906,
		CollAsgnRefID = 907,
		CollRptID = 908,
		CollInquiryID = 909,
		CollStatus = 910,
		TotNumReports = 911,
		LastRptRequested = 912,
		AgreementDesc = 913,
		AgreementID = 914,
		AgreementDate = 915,
		StartDate = 916,
		EndDate = 917,
		AgreementCurrency = 918,
		DeliveryType = 919,
		EndAccruedInterestAmt = 920,
		StartCash = 921,
		EndCash = 922,
		UserRequestID = 923,
		UserRequestType = 924,
		NewPassword = 925,
		UserStatus = 926,
		UserStatusText = 927,
		StatusValue = 928,
		StatusText = 929,
		RefCompID = 930,
		RefSubID = 931,
		NetworkResponseID = 932,
		NetworkRequestID = 933,
		LastNetworkResponseID = 934,
		NetworkRequestType = 935,
		NoCompIDs = 936,
		NetworkStatusResponseType = 937,
		NoCollInquiryQualifier = 938,
		TrdRptStatus = 939,
		AffirmStatus = 940,
		UnderlyingStrikeCurrency = 941,
		LegStrikeCurrency = 942,
		TimeBracket = 943,
		CollAction = 944,
		CollInquiryStatus = 945,
		CollInquiryResult = 946,
		StrikeCurrency = 947,
		NoNested3PartyIDs = 948,
		Nested3PartyID = 949,
		Nested3PartyIDSource = 950,
		Nested3PartyRole = 951,
		NoNested3PartySubIDs = 952,
		Nested3PartySubID = 953,
		Nested3PartySubIDType = 954,
		LegContractSettlMonth = 955,
		LegInterestAccrualDate = 956,
		CancelOnDisconnect = 9001,
		MDEntryMakerSide = 9002,
		EnableMDEntryMakerSide = 9003,
		MAX_VAL = 9004
	};

	constexpr char AdvSide_BUY = 'B';
	constexpr char AdvSide_SELL = 'S';
	constexpr char AdvSide_CROSS = 'X';
	constexpr char AdvSide_TRADE = 'T';
	constexpr char CommType_PER_UNIT = '1';
	constexpr char CommType_PERCENTAGE = '2';
	constexpr char CommType_ABSOLUTE = '3';
	constexpr char CommType_PERCENTAGE_WAIVED_CASH_DISCOUNT = '4';
	constexpr char CommType_PERCENTAGE_WAIVED_ENHANCED_UNITS = '5';
	constexpr char CommType_POINTS_PER_BOND_OR_OR_CONTRACT = '6';
	constexpr char HandlInst_AUTOMATED_EXECUTION_ORDER_PRIVATE = '1';
	constexpr char HandlInst_AUTOMATED_EXECUTION_ORDER_PUBLIC = '2';
	constexpr char HandlInst_MANUAL_ORDER = '3';
	constexpr char IOIQltyInd_LOW = 'L';
	constexpr char IOIQltyInd_MEDIUM = 'M';
	constexpr char IOIQltyInd_HIGH = 'H';
	constexpr char IOITransType_NEW = 'N';
	constexpr char IOITransType_CANCEL = 'C';
	constexpr char IOITransType_REPLACE = 'R';
	constexpr char LastCapacity_AGENT = '1';
	constexpr char LastCapacity_CROSS_AS_AGENT = '2';
	constexpr char LastCapacity_CROSS_AS_PRINCIPAL = '3';
	constexpr char LastCapacity_PRINCIPAL = '4';
	constexpr char OrdStatus_NEW = '0';
	constexpr char OrdStatus_PARTIALLY_FILLED = '1';
	constexpr char OrdStatus_FILLED = '2';
	constexpr char OrdStatus_DONE_FOR_DAY = '3';
	constexpr char OrdStatus_CANCELED = '4';
	constexpr char OrdStatus_REPLACED = '5';
	constexpr char OrdStatus_PENDING_CANCEL = '6';
	constexpr char OrdStatus_STOPPED = '7';
	constexpr char OrdStatus_REJECTED = '8';
	constexpr char OrdStatus_SUSPENDED = '9';
	constexpr char OrdStatus_PENDING_NEW = 'A';
	constexpr char OrdStatus_CALCULATED = 'B';
	constexpr char OrdStatus_EXPIRED = 'C';
	constexpr char OrdStatus_ACCEPTED_FOR_BIDDING = 'D';
	constexpr char OrdStatus_PENDING_REPLACE = 'E';
	constexpr char OrdType_MARKET = '1';
	constexpr char OrdType_LIMIT = '2';
	constexpr char OrdType_STOP = '3';
	constexpr char OrdType_STOP_LIMIT = '4';
	constexpr char OrdType_MARKET_ON_CLOSE = '5';
	constexpr char OrdType_WITH_OR_WITHOUT = '6';
	constexpr char OrdType_LIMIT_OR_BETTER = '7';
	constexpr char OrdType_LIMIT_WITH_OR_WITHOUT = '8';
	constexpr char OrdType_ON_BASIS = '9';
	constexpr char OrdType_ON_CLOSE = 'A';
	constexpr char OrdType_LIMIT_ON_CLOSE = 'B';
	constexpr char OrdType_FOREX_MARKET = 'C';
	constexpr char OrdType_PREVIOUSLY_QUOTED = 'D';
	constexpr char OrdType_PREVIOUSLY_INDICATED = 'E';
	constexpr char OrdType_FOREX_LIMIT = 'F';
	constexpr char OrdType_FOREX_SWAP = 'G';
	constexpr char OrdType_FOREX_PREVIOUSLY_QUOTED = 'H';
	constexpr char OrdType_FUNARI = 'I';
	constexpr char OrdType_MARKET_IF_TOUCHED = 'J';
	constexpr char OrdType_MARKET_WITH_LEFTOVER_AS_LIMIT = 'K';
	constexpr char OrdType_PREVIOUS_FUND_VALUATION_POINT = 'L';
	constexpr char OrdType_NEXT_FUND_VALUATION_POINT = 'M';
	constexpr char OrdType_PEGGED = 'P';
	constexpr char Side_BUY = '1';
	constexpr char Side_SELL = '2';
	constexpr char Side_BUY_MINUS = '3';
	constexpr char Side_SELL_PLUS = '4';
	constexpr char Side_SELL_SHORT = '5';
	constexpr char Side_SELL_SHORT_EXEMPT = '6';
	constexpr char Side_UNDISCLOSED = '7';
	constexpr char Side_CROSS = '8';
	constexpr char Side_CROSS_SHORT = '9';
	constexpr char Side_CROSS_SHORT_EXEMPT = 'A';
	constexpr char Side_AS_DEFINED = 'B';
	constexpr char Side_OPPOSITE = 'C';
	constexpr char Side_SUBSCRIBE = 'D';
	constexpr char Side_REDEEM = 'E';
	constexpr char Side_LEND = 'F';
	constexpr char Side_BORROW = 'G';
	constexpr char TimeInForce_DAY = '0';
	constexpr char TimeInForce_GOOD_TILL_CANCEL = '1';
	constexpr char TimeInForce_AT_THE_OPENING = '2';
	constexpr char TimeInForce_IMMEDIATE_OR_CANCEL = '3';
	constexpr char TimeInForce_FILL_OR_KILL = '4';
	constexpr char TimeInForce_GOOD_TILL_CROSSING = '5';
	constexpr char TimeInForce_GOOD_TILL_DATE = '6';
	constexpr char TimeInForce_AT_THE_CLOSE = '7';
	constexpr char Urgency_NORMAL = '0';
	constexpr char Urgency_FLASH = '1';
	constexpr char Urgency_BACKGROUND = '2';
	constexpr char SettlType_REGULAR = '0';
	constexpr char SettlType_CASH = '1';
	constexpr char SettlType_NEXT_DAY = '2';
	constexpr char SettlType_T_PLUS_2 = '3';
	constexpr char SettlType_T_PLUS_3 = '4';
	constexpr char SettlType_T_PLUS_4 = '5';
	constexpr char SettlType_FUTURE = '6';
	constexpr char SettlType_WHEN_AND_IF_ISSUED = '7';
	constexpr char SettlType_SELLERS_OPTION = '8';
	constexpr char SettlType_T_PLUS_5 = '9';
	constexpr char AllocTransType_NEW = '0';
	constexpr char AllocTransType_REPLACE = '1';
	constexpr char AllocTransType_CANCEL = '2';
	constexpr char AllocTransType_PRELIMINARY = '3';
	constexpr char AllocTransType_CALCULATED = '4';
	constexpr char AllocTransType_CALCULATED_WITHOUT_PRELIMINARY = '5';
	constexpr char PositionEffect_OPEN = 'O';
	constexpr char PositionEffect_CLOSE = 'C';
	constexpr char PositionEffect_ROLLED = 'R';
	constexpr char PositionEffect_FIFO = 'F';
	constexpr char ProcessCode_REGULAR = '0';
	constexpr char ProcessCode_SOFT_DOLLAR = '1';
	constexpr char ProcessCode_STEP_IN = '2';
	constexpr char ProcessCode_STEP_OUT = '3';
	constexpr char ProcessCode_SOFT_DOLLAR_STEP_IN = '4';
	constexpr char ProcessCode_SOFT_DOLLAR_STEP_OUT = '5';
	constexpr char ProcessCode_PLAN_SPONSOR = '6';
	constexpr int AllocStatus_ACCEPTED = 0;
	constexpr int AllocStatus_BLOCK_LEVEL_REJECT = 1;
	constexpr int AllocStatus_ACCOUNT_LEVEL_REJECT = 2;
	constexpr int AllocStatus_RECEIVED = 3;
	constexpr int AllocStatus_INCOMPLETE = 4;
	constexpr int AllocStatus_REJECTED_BY_INTERMEDIARY = 5;
	constexpr int AllocRejCode_UNKNOWN_ACCOUNT = 0;
	constexpr int AllocRejCode_INCORRECT_QUANTITY = 1;
	constexpr int AllocRejCode_INCORRECT_AVERAGE_PRICE = 2;
	constexpr int AllocRejCode_UNKNOWN_EXECUTING_BROKER_MNEMONIC = 3;
	constexpr int AllocRejCode_COMMISSION_DIFFERENCE = 4;
	constexpr int AllocRejCode_UNKNOWN_ORDERID = 5;
	constexpr int AllocRejCode_UNKNOWN_LISTID = 6;
	constexpr int AllocRejCode_OTHER = 7;
	constexpr int AllocRejCode_INCORRECT_ALLOCATED_QUANTITY = 8;
	constexpr int AllocRejCode_CALCULATION_DIFFERENCE = 9;
	constexpr int AllocRejCode_UNKNOWN_OR_STALE_EXEC_ID = 10;
	constexpr int AllocRejCode_MISMATCHED_DATA_VALUE = 11;
	constexpr int AllocRejCode_UNKNOWN_CLORDID = 12;
	constexpr int AllocRejCode_WAREHOUSE_REQUEST_REJECTED = 13;
	constexpr char EmailType_NEW = '0';
	constexpr char EmailType_REPLY = '1';
	constexpr char EmailType_ADMIN_REPLY = '2';
	constexpr int EncryptMethod_NONE_OTHER = 0;
	constexpr int EncryptMethod_PKCS = 1;
	constexpr int EncryptMethod_DES = 2;
	constexpr int EncryptMethod_PKCS_DES = 3;
	constexpr int EncryptMethod_PGP_DES = 4;
	constexpr int EncryptMethod_PGP_DES_MD5 = 5;
	constexpr int EncryptMethod_PEM_DES_MD5 = 6;
	constexpr int CxlRejReason_TOO_LATE_TO_CANCEL = 0;
	constexpr int CxlRejReason_UNKNOWN_ORDER = 1;
	constexpr int CxlRejReason_BROKER_EXCHANGE_OPTION = 2;
	constexpr int CxlRejReason_ORDER_ALREADY_IN_PENDING_CANCEL_OR_PENDING_REPLACE_STATUS = 3;
	constexpr int CxlRejReason_UNABLE_TO_PROCESS_ORDER_MASS_CANCEL_REQUEST = 4;
	constexpr int CxlRejReason_ORIGORDMODTIME_DID_NOT_MATCH_LAST_TRANSACTTIME_OF_ORDER = 5;
	constexpr int CxlRejReason_DUPLICATE_CLORDID_RECEIVED = 6;
	constexpr int CxlRejReason_OTHER = 99;
	constexpr int OrdRejReason_BROKER_EXCHANGE_OPTION = 0;
	constexpr int OrdRejReason_UNKNOWN_SYMBOL = 1;
	constexpr int OrdRejReason_EXCHANGE_CLOSED = 2;
	constexpr int OrdRejReason_ORDER_EXCEEDS_LIMIT = 3;
	constexpr int OrdRejReason_TOO_LATE_TO_ENTER = 4;
	constexpr int OrdRejReason_UNKNOWN_ORDER = 5;
	constexpr int OrdRejReason_DUPLICATE_ORDER = 6;
	constexpr int OrdRejReason_DUPLICATE_OF_A_VERBALLY_COMMUNICATED_ORDER = 7;
	constexpr int OrdRejReason_STALE_ORDER = 8;
	constexpr int OrdRejReason_TRADE_ALONG_REQUIRED = 9;
	constexpr int OrdRejReason_INVALID_INVESTOR_ID = 10;
	constexpr int OrdRejReason_UNSUPPORTED_ORDER_CHARACTERISTIC = 11;
	constexpr int OrdRejReason_SURVEILLENCE_OPTION = 12;
	constexpr int OrdRejReason_INCORRECT_QUANTITY = 13;
	constexpr int OrdRejReason_INCORRECT_ALLOCATED_QUANTITY = 14;
	constexpr int OrdRejReason_UNKNOWN_ACCOUNT = 15;
	constexpr int OrdRejReason_OTHER = 99;
	constexpr char IOIQualifier_ALL_OR_NONE = 'A';
	constexpr char IOIQualifier_MARKET_ON_CLOSE = 'B';
	constexpr char IOIQualifier_AT_THE_CLOSE = 'C';
	constexpr char IOIQualifier_VWAP = 'D';
	constexpr char IOIQualifier_IN_TOUCH_WITH = 'I';
	constexpr char IOIQualifier_LIMIT = 'L';
	constexpr char IOIQualifier_MORE_BEHIND = 'M';
	constexpr char IOIQualifier_AT_THE_OPEN = 'O';
	constexpr char IOIQualifier_TAKING_A_POSITION = 'P';
	constexpr char IOIQualifier_AT_THE_MARKET = 'Q';
	constexpr char IOIQualifier_READY_TO_TRADE = 'R';
	constexpr char IOIQualifier_PORTFOLIO_SHOWN = 'S';
	constexpr char IOIQualifier_THROUGH_THE_DAY = 'T';
	constexpr char IOIQualifier_VERSUS = 'V';
	constexpr char IOIQualifier_INDICATION_WORKING_AWAY = 'W';
	constexpr char IOIQualifier_CROSSING_OPPORTUNITY = 'X';
	constexpr char IOIQualifier_AT_THE_MIDPOINT = 'Y';
	constexpr char IOIQualifier_PRE_OPEN = 'Z';
	constexpr char DKReason_UNKNOWN_SYMBOL = 'A';
	constexpr char DKReason_WRONG_SIDE = 'B';
	constexpr char DKReason_QUANTITY_EXCEEDS_ORDER = 'C';
	constexpr char DKReason_NO_MATCHING_ORDER = 'D';
	constexpr char DKReason_PRICE_EXCEEDS_LIMIT = 'E';
	constexpr char DKReason_CALCULATION_DIFFERENCE = 'F';
	constexpr char DKReason_OTHER = 'Z';
	constexpr char MiscFeeType_REGULATORY = '1';
	constexpr char MiscFeeType_TAX = '2';
	constexpr char MiscFeeType_LOCAL_COMMISSION = '3';
	constexpr char MiscFeeType_EXCHANGE_FEES = '4';
	constexpr char MiscFeeType_STAMP = '5';
	constexpr char MiscFeeType_LEVY = '6';
	constexpr char MiscFeeType_OTHER = '7';
	constexpr char MiscFeeType_MARKUP = '8';
	constexpr char MiscFeeType_CONSUMPTION_TAX = '9';
	constexpr char MiscFeeType_PER_TRANSACTION = '10';
	constexpr char MiscFeeType_CONVERSION = '11';
	constexpr char MiscFeeType_AGENT = '12';
	constexpr char ExecType_NEW = '0';
	constexpr char ExecType_PARTIAL_FILL = '1';
	constexpr char ExecType_FILL = '2';
	constexpr char ExecType_DONE_FOR_DAY = '3';
	constexpr char ExecType_CANCELED = '4';
	constexpr char ExecType_REPLACE = '5';
	constexpr char ExecType_PENDING_CANCEL = '6';
	constexpr char ExecType_STOPPED = '7';
	constexpr char ExecType_REJECTED = '8';
	constexpr char ExecType_SUSPENDED = '9';
	constexpr char ExecType_PENDING_NEW = 'A';
	constexpr char ExecType_CALCULATED = 'B';
	constexpr char ExecType_EXPIRED = 'C';
	constexpr char ExecType_RESTATED = 'D';
	constexpr char ExecType_PENDING_REPLACE = 'E';
	constexpr char ExecType_TRADE = 'F';
	constexpr char ExecType_TRADE_CORRECT = 'G';
	constexpr char ExecType_TRADE_CANCEL = 'H';
	constexpr char ExecType_ORDER_STATUS = 'I';
	constexpr char SettlCurrFxRateCalc_MULTIPLY = 'M';
	constexpr char SettlCurrFxRateCalc_DIVIDE = 'D';
	constexpr char SettlInstMode_DEFAULT = '0';
	constexpr char SettlInstMode_STANDING_INSTRUCTIONS_PROVIDED = '1';
	constexpr char SettlInstMode_SPECIFIC_ORDER_FOR_A_SINGLE_ACCOUNT = '4';
	constexpr char SettlInstMode_REQUEST_REJECT = '5';
	constexpr char SettlInstTransType_NEW = 'N';
	constexpr char SettlInstTransType_CANCEL = 'C';
	constexpr char SettlInstTransType_REPLACE = 'R';
	constexpr char SettlInstTransType_RESTATE = 'T';
	constexpr char SettlInstSource_BROKERS_INSTRUCTIONS = '1';
	constexpr char SettlInstSource_INSTITUTIONS_INSTRUCTIONS = '2';
	constexpr char SettlInstSource_INVESTOR = '3';
	constexpr int StandInstDbType_OTHER = 0;
	constexpr int StandInstDbType_DTC_SID = 1;
	constexpr int StandInstDbType_THOMSON_ALERT = 2;
	constexpr int StandInstDbType_A_GLOBAL_CUSTODIAN = 3;
	constexpr int StandInstDbType_ACCOUNTNET = 4;
	constexpr int SettlDeliveryType_VERSUS_PAYMENT = 0;
	constexpr int SettlDeliveryType_FREE = 1;
	constexpr int SettlDeliveryType_TRI_PARTY = 2;
	constexpr int SettlDeliveryType_HOLD_IN_CUSTODY = 3;
	constexpr int AllocLinkType_F_X_NETTING = 0;
	constexpr int AllocLinkType_F_X_SWAP = 1;
	constexpr int PutOrCall_PUT = 0;
	constexpr int PutOrCall_CALL = 1;
	constexpr int CoveredOrUncovered_COVERED = 0;
	constexpr int CoveredOrUncovered_UNCOVERED = 1;
	constexpr int AllocHandlInst_MATCH = 1;
	constexpr int AllocHandlInst_FORWARD = 2;
	constexpr int AllocHandlInst_FORWARD_AND_MATCH = 3;
	constexpr int RoutingType_TARGET_FIRM = 1;
	constexpr int RoutingType_TARGET_LIST = 2;
	constexpr int RoutingType_BLOCK_FIRM = 3;
	constexpr int RoutingType_BLOCK_LIST = 4;
	constexpr char SubscriptionRequestType_SNAPSHOT = '0';
	constexpr char SubscriptionRequestType_SNAPSHOT_PLUS_UPDATES = '1';
	constexpr char SubscriptionRequestType_DISABLE_PREVIOUS_SNAPSHOT_PLUS_UPDATE_REQUEST = '2';
	constexpr int MarketDepth_FULL_BOOK = 0;
	constexpr int MarketDepth_TOP_OF_BOOK = 1;
	constexpr int MDUpdateType_FULL_REFRESH = 0;
	constexpr int MDUpdateType_INCREMENTAL_REFRESH = 1;
	constexpr char MDEntryType_BID = '0';
	constexpr char MDEntryType_OFFER = '1';
	constexpr char MDEntryType_TRADE = '2';
	constexpr char MDEntryType_INDEX_VALUE = '3';
	constexpr char MDEntryType_OPENING_PRICE = '4';
	constexpr char MDEntryType_CLOSING_PRICE = '5';
	constexpr char MDEntryType_SETTLEMENT_PRICE = '6';
	constexpr char MDEntryType_TRADING_SESSION_HIGH_PRICE = '7';
	constexpr char MDEntryType_TRADING_SESSION_LOW_PRICE = '8';
	constexpr char MDEntryType_TRADING_SESSION_VWAP_PRICE = '9';
	constexpr char MDEntryType_IMBALANCE = 'A';
	constexpr char MDEntryType_TRADE_VOLUME = 'B';
	constexpr char MDEntryType_OPEN_INTEREST = 'C';
	constexpr char MDEntryType_AUCTION_CLEARING_PRICE = 'Q';
	constexpr char TickDirection_PLUS_TICK = '0';
	constexpr char TickDirection_ZERO_PLUS_TICK = '1';
	constexpr char TickDirection_MINUS_TICK = '2';
	constexpr char TickDirection_ZERO_MINUS_TICK = '3';
	constexpr char MDUpdateAction_NEW = '0';
	constexpr char MDUpdateAction_CHANGE = '1';
	constexpr char MDUpdateAction_DELETE = '2';
	constexpr char MDReqRejReason_UNKNOWN_SYMBOL = '0';
	constexpr char MDReqRejReason_DUPLICATE_MDREQID = '1';
	constexpr char MDReqRejReason_INSUFFICIENT_BANDWIDTH = '2';
	constexpr char MDReqRejReason_INSUFFICIENT_PERMISSIONS = '3';
	constexpr char MDReqRejReason_UNSUPPORTED_SUBSCRIPTIONREQUESTTYPE = '4';
	constexpr char MDReqRejReason_UNSUPPORTED_MARKETDEPTH = '5';
	constexpr char MDReqRejReason_UNSUPPORTED_MDUPDATETYPE = '6';
	constexpr char MDReqRejReason_UNSUPPORTED_AGGREGATEDBOOK = '7';
	constexpr char MDReqRejReason_UNSUPPORTED_MDENTRYTYPE = '8';
	constexpr char MDReqRejReason_UNSUPPORTED_TRADINGSESSIONID = '9';
	constexpr char MDReqRejReason_UNSUPPORTED_SCOPE = 'A';
	constexpr char MDReqRejReason_UNSUPPORTED_OPENCLOSESETTLEFLAG = 'B';
	constexpr char MDReqRejReason_UNSUPPORTED_MDIMPLICITDELETE = 'C';
	constexpr char DeleteReason_CANCELATION_TRADE_BUST = '0';
	constexpr char DeleteReason_ERROR = '1';
	constexpr int QuoteStatus_ACCEPTED = 0;
	constexpr int QuoteStatus_CANCELED_FOR_SYMBOL = 1;
	constexpr int QuoteStatus_CANCELED_FOR_SECURITY_TYPE = 2;
	constexpr int QuoteStatus_CANCELED_FOR_UNDERLYING = 3;
	constexpr int QuoteStatus_CANCELED_ALL = 4;
	constexpr int QuoteStatus_REJECTED = 5;
	constexpr int QuoteStatus_REMOVED_FROM_MARKET = 6;
	constexpr int QuoteStatus_EXPIRED = 7;
	constexpr int QuoteStatus_QUERY = 8;
	constexpr int QuoteStatus_QUOTE_NOT_FOUND = 9;
	constexpr int QuoteStatus_PENDING = 10;
	constexpr int QuoteStatus_PASS = 11;
	constexpr int QuoteStatus_LOCKED_MARKET_WARNING = 12;
	constexpr int QuoteStatus_CROSS_MARKET_WARNING = 13;
	constexpr int QuoteStatus_CANCELED_DUE_TO_LOCK_MARKET = 14;
	constexpr int QuoteStatus_CANCELED_DUE_TO_CROSS_MARKET = 15;
	constexpr int QuoteCancelType_CANCEL_FOR_SYMBOL = 1;
	constexpr int QuoteCancelType_CANCEL_FOR_SECURITY_TYPE = 2;
	constexpr int QuoteCancelType_CANCEL_FOR_UNDERLYING_SYMBOL = 3;
	constexpr int QuoteCancelType_CANCEL_ALL_QUOTES = 4;
	constexpr int QuoteRejectReason_UNKNOWN_SYMBOL = 1;
	constexpr int QuoteRejectReason_EXCHANGE_CLOSED = 2;
	constexpr int QuoteRejectReason_QUOTE_REQUEST_EXCEEDS_LIMIT = 3;
	constexpr int QuoteRejectReason_TOO_LATE_TO_ENTER = 4;
	constexpr int QuoteRejectReason_UNKNOWN_QUOTE = 5;
	constexpr int QuoteRejectReason_DUPLICATE_QUOTE = 6;
	constexpr int QuoteRejectReason_INVALID_BID_ASK_SPREAD = 7;
	constexpr int QuoteRejectReason_INVALID_PRICE = 8;
	constexpr int QuoteRejectReason_NOT_AUTHORIZED_TO_QUOTE_SECURITY = 9;
	constexpr int QuoteRejectReason_OTHER = 99;
	constexpr int QuoteResponseLevel_NO_ACKNOWLEDGEMENT = 0;
	constexpr int QuoteResponseLevel_ACKNOWLEDGE_ONLY_NEGATIVE_OR_ERRONEOUS_QUOTES = 1;
	constexpr int QuoteResponseLevel_ACKNOWLEDGE_EACH_QUOTE_MESSAGES = 2;
	constexpr int QuoteRequestType_MANUAL = 1;
	constexpr int QuoteRequestType_AUTOMATIC = 2;
	constexpr int UnderlyingPutOrCall_PUT = 0;
	constexpr int UnderlyingPutOrCall_CALL = 1;
	constexpr int SecurityRequestType_REQUEST_SECURITY_IDENTITY_AND_SPECIFICATIONS = 0;
	constexpr int SecurityRequestType_REQUEST_SECURITY_IDENTITY_FOR_THE_SPECIFICATIONS_PROVIDED = 1;
	constexpr int SecurityRequestType_REQUEST_LIST_SECURITY_TYPES = 2;
	constexpr int SecurityRequestType_REQUEST_LIST_SECURITIES = 3;
	constexpr int SecurityResponseType_ACCEPT_SECURITY_PROPOSAL_AS_IS = 1;
	constexpr int SecurityResponseType_ACCEPT_SECURITY_PROPOSAL_WITH_REVISIONS_AS_INDICATED_IN_THE_MESSAGE = 2;
	constexpr int SecurityResponseType_LIST_OF_SECURITY_TYPES_RETURNED_PER_REQUEST = 3;
	constexpr int SecurityResponseType_LIST_OF_SECURITIES_RETURNED_PER_REQUEST = 4;
	constexpr int SecurityResponseType_REJECT_SECURITY_PROPOSAL = 5;
	constexpr int SecurityResponseType_CAN_NOT_MATCH_SELECTION_CRITERIA = 6;
	constexpr int SecurityTradingStatus_OPENING_DELAY = 1;
	constexpr int SecurityTradingStatus_TRADING_HALT = 2;
	constexpr int SecurityTradingStatus_RESUME = 3;
	constexpr int SecurityTradingStatus_NO_OPEN_NO_RESUME = 4;
	constexpr int SecurityTradingStatus_PRICE_INDICATION = 5;
	constexpr int SecurityTradingStatus_TRADING_RANGE_INDICATION = 6;
	constexpr int SecurityTradingStatus_MARKET_IMBALANCE_BUY = 7;
	constexpr int SecurityTradingStatus_MARKET_IMBALANCE_SELL = 8;
	constexpr int SecurityTradingStatus_MARKET_ON_CLOSE_IMBALANCE_BUY = 9;
	constexpr int SecurityTradingStatus_MARKET_ON_CLOSE_IMBALANCE_SELL = 10;
	constexpr int SecurityTradingStatus_NOT_ASSIGNED = 11;
	constexpr int SecurityTradingStatus_NO_MARKET_IMBALANCE = 12;
	constexpr int SecurityTradingStatus_NO_MARKET_ON_CLOSE_IMBALANCE = 13;
	constexpr int SecurityTradingStatus_ITS_PRE_OPENING = 14;
	constexpr int SecurityTradingStatus_NEW_PRICE_INDICATION = 15;
	constexpr int SecurityTradingStatus_TRADE_DISSEMINATION_TIME = 16;
	constexpr int SecurityTradingStatus_READY_TO_TRADE_START_OF_SESSION = 17;
	constexpr int SecurityTradingStatus_NOT_AVAILABLE_FOR_TRADING_END_OF_SESSION = 18;
	constexpr int SecurityTradingStatus_NOT_TRADED_ON_THIS_MARKET = 19;
	constexpr int SecurityTradingStatus_UNKNOWN_OR_INVALID = 20;
	constexpr int SecurityTradingStatus_PRE_OPEN = 21;
	constexpr int SecurityTradingStatus_OPENING_ROTATION = 22;
	constexpr int SecurityTradingStatus_FAST_MARKET = 23;
	constexpr char HaltReason_ORDER_IMBALANCE = 'I';
	constexpr char HaltReason_EQUIPMENT_CHANGEOVER = 'X';
	constexpr char HaltReason_NEWS_PENDING = 'P';
	constexpr char HaltReason_NEWS_DISSEMINATION = 'D';
	constexpr char HaltReason_ORDER_INFLUX = 'E';
	constexpr char HaltReason_ADDITIONAL_INFORMATION = 'M';
	constexpr int Adjustment_CANCEL = 1;
	constexpr int Adjustment_ERROR = 2;
	constexpr int Adjustment_CORRECTION = 3;
	constexpr int TradSesMethod_ELECTRONIC = 1;
	constexpr int TradSesMethod_OPEN_OUTCRY = 2;
	constexpr int TradSesMethod_TWO_PARTY = 3;
	constexpr int TradSesMode_TESTING = 1;
	constexpr int TradSesMode_SIMULATED = 2;
	constexpr int TradSesMode_PRODUCTION = 3;
	constexpr int TradSesStatus_UNKNOWN = 0;
	constexpr int TradSesStatus_HALTED = 1;
	constexpr int TradSesStatus_OPEN = 2;
	constexpr int TradSesStatus_CLOSED = 3;
	constexpr int TradSesStatus_PRE_OPEN = 4;
	constexpr int TradSesStatus_PRE_CLOSE = 5;
	constexpr int TradSesStatus_REQUEST_REJECTED = 6;
	constexpr int QuoteEntryRejectReason_UNKNOWN_SYMBOL = 1;
	constexpr int QuoteEntryRejectReason_EXCHANGE_CLOSED = 2;
	constexpr int QuoteEntryRejectReason_QUOTE_EXCEEDS_LIMIT = 3;
	constexpr int QuoteEntryRejectReason_TOO_LATE_TO_ENTER = 4;
	constexpr int QuoteEntryRejectReason_UNKNOWN_QUOTE = 5;
	constexpr int QuoteEntryRejectReason_DUPLICATE_QUOTE = 6;
	constexpr int QuoteEntryRejectReason_INVALID_BID_ASK_SPREAD = 7;
	constexpr int QuoteEntryRejectReason_INVALID_PRICE = 8;
	constexpr int QuoteEntryRejectReason_NOT_AUTHORIZED_TO_QUOTE_SECURITY = 9;
	constexpr int SessionRejectReason_INVALID_TAG_NUMBER = 0;
	constexpr int SessionRejectReason_REQUIRED_TAG_MISSING = 1;
	constexpr int SessionRejectReason_TAG_NOT_DEFINED_FOR_THIS_MESSAGE_TYPE = 2;
	constexpr int SessionRejectReason_UNDEFINED_TAG = 3;
	constexpr int SessionRejectReason_TAG_SPECIFIED_WITHOUT_A_VALUE = 4;
	constexpr int SessionRejectReason_VALUE_IS_INCORRECT = 5;
	constexpr int SessionRejectReason_INCORRECT_DATA_FORMAT_FOR_VALUE = 6;
	constexpr int SessionRejectReason_DECRYPTION_PROBLEM = 7;
	constexpr int SessionRejectReason_SIGNATURE_PROBLEM = 8;
	constexpr int SessionRejectReason_COMPID_PROBLEM = 9;
	constexpr int SessionRejectReason_SENDINGTIME_ACCURACY_PROBLEM = 10;
	constexpr int SessionRejectReason_INVALID_MSGTYPE = 11;
	constexpr int SessionRejectReason_XML_VALIDATION_ERROR = 12;
	constexpr int SessionRejectReason_TAG_APPEARS_MORE_THAN_ONCE = 13;
	constexpr int SessionRejectReason_TAG_SPECIFIED_OUT_OF_REQUIRED_ORDER = 14;
	constexpr int SessionRejectReason_REPEATING_GROUP_FIELDS_OUT_OF_ORDER = 15;
	constexpr int SessionRejectReason_INCORRECT_NUMINGROUP_COUNT_FOR_REPEATING_GROUP = 16;
	constexpr int SessionRejectReason_NON_DATA_VALUE_INCLUDES_FIELD_DELIMITER = 17;
	constexpr int SessionRejectReason_OTHER = 99;
	constexpr char BidRequestTransType_NEW = 'N';
	constexpr char BidRequestTransType_CANCEL = 'C';
	constexpr int ExecRestatementReason_GT_CORPORATE_ACTION = 0;
	constexpr int ExecRestatementReason_GT_RENEWAL_RESTATEMENT = 1;
	constexpr int ExecRestatementReason_VERBAL_CHANGE = 2;
	constexpr int ExecRestatementReason_REPRICING_OF_ORDER = 3;
	constexpr int ExecRestatementReason_BROKER_OPTION = 4;
	constexpr int ExecRestatementReason_PARTIAL_DECLINE_OF_ORDERQTY = 5;
	constexpr int ExecRestatementReason_CANCEL_ON_TRADING_HALT = 6;
	constexpr int ExecRestatementReason_CANCEL_ON_SYSTEM_FAILURE = 7;
	constexpr int ExecRestatementReason_MARKET_OPTION = 8;
	constexpr int ExecRestatementReason_CANCELED_NOT_BEST = 9;
	constexpr int ExecRestatementReason_WAREHOUSE_RECAP = 10;
	constexpr int ExecRestatementReason_OTHER = 99;
	constexpr int BusinessRejectReason_OTHER = 0;
	constexpr int BusinessRejectReason_UNKOWN_ID = 1;
	constexpr int BusinessRejectReason_UNKNOWN_SECURITY = 2;
	constexpr int BusinessRejectReason_UNSUPPORTED_MESSAGE_TYPE = 3;
	constexpr int BusinessRejectReason_APPLICATION_NOT_AVAILABLE = 4;
	constexpr int BusinessRejectReason_CONDITIONALLY_REQUIRED_FIELD_MISSING = 5;
	constexpr int BusinessRejectReason_NOT_AUTHORIZED = 6;
	constexpr int BusinessRejectReason_DELIVERTO_FIRM_NOT_AVAILABLE_AT_THIS_TIME = 7;
	constexpr char MsgDirection_SEND = 'S';
	constexpr char MsgDirection_RECEIVE = 'R';
	constexpr char DiscretionInst_RELATED_TO_DISPLAYED_PRICE = '0';
	constexpr char DiscretionInst_RELATED_TO_MARKET_PRICE = '1';
	constexpr char DiscretionInst_RELATED_TO_PRIMARY_PRICE = '2';
	constexpr char DiscretionInst_RELATED_TO_LOCAL_PRIMARY_PRICE = '3';
	constexpr char DiscretionInst_RELATED_TO_MIDPOINT_PRICE = '4';
	constexpr char DiscretionInst_RELATED_TO_LAST_TRADE_PRICE = '5';
	constexpr char DiscretionInst_RELATED_TO_VWAP = '6';
	constexpr int BidType_NON_DISCLOSED = 1;
	constexpr int BidType_DISCLOSED_STYLE = 2;
	constexpr int BidType_NO_BIDDING_PROCESS = 3;
	constexpr int BidDescriptorType_SECTOR = 1;
	constexpr int BidDescriptorType_COUNTRY = 2;
	constexpr int BidDescriptorType_INDEX = 3;
	constexpr int SideValueInd_SIDEVALUE1 = 1;
	constexpr int SideValueInd_SIDEVALUE2 = 2;
	constexpr int LiquidityIndType_FIVEDAY_MOVING_AVERAGE = 1;
	constexpr int LiquidityIndType_TWENTYDAY_MOVING_AVERAGE = 2;
	constexpr int LiquidityIndType_NORMAL_MARKET_SIZE = 3;
	constexpr int LiquidityIndType_OTHER = 4;
	constexpr int ProgRptReqs_BUYSIDE_EXPLICITLY_REQUESTS_STATUS_USING_STATUSREQUEST = 1;
	constexpr int ProgRptReqs_SELLSIDE_PERIODICALLY_SENDS_STATUS_USING_LISTSTATUS = 2;
	constexpr int ProgRptReqs_REAL_TIME_EXECUTION_REPORTS = 3;
	constexpr int IncTaxInd_NET = 1;
	constexpr int IncTaxInd_GROSS = 2;
	constexpr char BidTradeType_RISK_TRADE = 'R';
	constexpr char BidTradeType_VWAP_GUARANTEE = 'G';
	constexpr char BidTradeType_AGENCY = 'A';
	constexpr char BidTradeType_GUARANTEED_CLOSE = 'J';
	constexpr char BasisPxType_CLOSING_PRICE_AT_MORNING_SESSION = '2';
	constexpr char BasisPxType_CLOSING_PRICE = '3';
	constexpr char BasisPxType_CURRENT_PRICE = '4';
	constexpr char BasisPxType_SQ = '5';
	constexpr char BasisPxType_VWAP_THROUGH_A_DAY = '6';
	constexpr char BasisPxType_VWAP_THROUGH_A_MORNING_SESSION = '7';
	constexpr char BasisPxType_VWAP_THROUGH_AN_AFTERNOON_SESSION = '8';
	constexpr char BasisPxType_VWAP_THROUGH_A_DAY_EXCEPT_YORI = '9';
	constexpr char BasisPxType_VWAP_THROUGH_A_MORNING_SESSION_EXCEPT_YORI = 'A';
	constexpr char BasisPxType_VWAP_THROUGH_AN_AFTERNOON_SESSION_EXCEPT_YORI = 'B';
	constexpr char BasisPxType_STRIKE = 'C';
	constexpr char BasisPxType_OPEN = 'D';
	constexpr char BasisPxType_OTHERS = 'Z';
	constexpr int PriceType_PERCENTAGE = 1;
	constexpr int PriceType_PER_UNIT = 2;
	constexpr int PriceType_FIXED_AMOUNT = 3;
	constexpr int PriceType_DISCOUNT = 4;
	constexpr int PriceType_PREMIUM = 5;
	constexpr int PriceType_SPREAD = 6;
	constexpr int PriceType_TED_PRICE = 7;
	constexpr int PriceType_TED_YIELD = 8;
	constexpr int PriceType_YIELD = 9;
	constexpr int PriceType_FIXED_CABINET_TRADE_PRICE = 10;
	constexpr int PriceType_VARIABLE_CABINET_TRADE_PRICE = 11;
	constexpr int GTBookingInst_BOOK_OUT_ALL_TRADES_ON_DAY_OF_EXECUTION = 0;
	constexpr int GTBookingInst_ACCUMULATE_EXECUTIONS_UNTIL_ORDER_IS_FILLED_OR_EXPIRES = 1;
	constexpr int GTBookingInst_ACCUMULATE_UNTIL_VERBALLY_NOTIFIED_OTHERWISE = 2;
	constexpr int ListStatusType_ACK = 1;
	constexpr int ListStatusType_RESPONSE = 2;
	constexpr int ListStatusType_TIMED = 3;
	constexpr int ListStatusType_EXECSTARTED = 4;
	constexpr int ListStatusType_ALLDONE = 5;
	constexpr int ListStatusType_ALERT = 6;
	constexpr int NetGrossInd_NET = 1;
	constexpr int NetGrossInd_GROSS = 2;
	constexpr int ListOrderStatus_INBIDDINGPROCESS = 1;
	constexpr int ListOrderStatus_RECEIVEDFOREXECUTION = 2;
	constexpr int ListOrderStatus_EXECUTING = 3;
	constexpr int ListOrderStatus_CANCELING = 4;
	constexpr int ListOrderStatus_ALERT = 5;
	constexpr int ListOrderStatus_ALL_DONE = 6;
	constexpr int ListOrderStatus_REJECT = 7;
	constexpr char ListExecInstType_IMMEDIATE = '1';
	constexpr char ListExecInstType_WAIT_FOR_EXECUTE_INSTRUCTION = '2';
	constexpr char ListExecInstType_EXCHANGE_SWITCH_CIV_ORDER_SELL_DRIVEN = '3';
	constexpr char ListExecInstType_EXCHANGE_SWITCH_CIV_ORDER_BUY_DRIVEN_CASH_TOP_UP = '4';
	constexpr char ListExecInstType_EXCHANGE_SWITCH_CIV_ORDER_BUY_DRIVEN_CASH_WITHDRAW = '5';
	constexpr char CxlRejResponseTo_ORDER_CANCEL_REQUEST = '1';
	constexpr char CxlRejResponseTo_ORDER_CANCEL_REPLACE_REQUEST = '2';
	constexpr char MultiLegReportingType_SINGLE_SECURITY = '1';
	constexpr char MultiLegReportingType_INDIVIDUAL_LEG_OF_A_MULTI_LEG_SECURITY = '2';
	constexpr char MultiLegReportingType_MULTI_LEG_SECURITY = '3';
	constexpr char PartyIDSource_BIC = 'B';
	constexpr char PartyIDSource_GENERALLY_ACCEPTED_MARKET_PARTICIPANT_IDENTIFIER = 'C';
	constexpr char PartyIDSource_PROPRIETARY_CUSTOM_CODE = 'D';
	constexpr char PartyIDSource_ISO_COUNTRY_CODE = 'E';
	constexpr char PartyIDSource_SETTLEMENT_ENTITY_LOCATION = 'F';
	constexpr char PartyIDSource_MIC = 'G';
	constexpr char PartyIDSource_CSD_PARTICIPANT_MEMBER_CODE = 'H';
	constexpr char PartyIDSource_KOREAN_INVESTOR_ID = '1';
	constexpr char PartyIDSource_TAIWANESE_QUALIFIED_FOREIGN_INVESTOR_ID_QFII_FID = '2';
	constexpr char PartyIDSource_TAIWANESE_TRADING_ACCOUNT = '3';
	constexpr char PartyIDSource_MALAYSIAN_CENTRAL_DEPOSITORY_NUMBER = '4';
	constexpr char PartyIDSource_CHINESE_B_SHARE = '5';
	constexpr char PartyIDSource_UK_NATIONAL_INSURANCE_OR_PENSION_NUMBER = '6';
	constexpr char PartyIDSource_US_SOCIAL_SECURITY_NUMBER = '7';
	constexpr char PartyIDSource_US_EMPLOYER_IDENTIFICATION_NUMBER = '8';
	constexpr char PartyIDSource_AUSTRALIAN_BUSINESS_NUMBER = '9';
	constexpr char PartyIDSource_AUSTRALIAN_TAX_FILE_NUMBER = 'A';
	constexpr char PartyIDSource_DIRECTED_BROKER = 'I';
	constexpr int PartyRole_EXECUTING_FIRM = 1;
	constexpr int PartyRole_BROKER_OF_CREDIT = 2;
	constexpr int PartyRole_CLIENT_ID = 3;
	constexpr int PartyRole_CLEARING_FIRM = 4;
	constexpr int PartyRole_INVESTOR_ID = 5;
	constexpr int PartyRole_INTRODUCING_FIRM = 6;
	constexpr int PartyRole_ENTERING_FIRM = 7;
	constexpr int PartyRole_LOCATE_LENDING_FIRM = 8;
	constexpr int PartyRole_FUND_MANAGER_CLIENT_ID = 9;
	constexpr int PartyRole_SETTLEMENT_LOCATION = 10;
	constexpr int PartyRole_ORDER_ORIGINATION_TRADER = 11;
	constexpr int PartyRole_EXECUTING_TRADER = 12;
	constexpr int PartyRole_ORDER_ORIGINATION_FIRM = 13;
	constexpr int PartyRole_GIVEUP_CLEARING_FIRM = 14;
	constexpr int PartyRole_CORRESPONDANT_CLEARING_FIRM = 15;
	constexpr int PartyRole_EXECUTING_SYSTEM = 16;
	constexpr int PartyRole_CONTRA_FIRM = 17;
	constexpr int PartyRole_CONTRA_CLEARING_FIRM = 18;
	constexpr int PartyRole_SPONSORING_FIRM = 19;
	constexpr int PartyRole_UNDERLYING_CONTRA_FIRM = 20;
	constexpr int PartyRole_CLEARING_ORGANIZATION = 21;
	constexpr int PartyRole_EXCHANGE = 22;
	constexpr int PartyRole_CUSTOMER_ACCOUNT = 24;
	constexpr int PartyRole_CORRESPONDENT_CLEARING_ORGANIZATION = 25;
	constexpr int PartyRole_CORRESPONDENT_BROKER = 26;
	constexpr int PartyRole_BUYER_SELLER = 27;
	constexpr int PartyRole_CUSTODIAN = 28;
	constexpr int PartyRole_INTERMEDIARY = 29;
	constexpr int PartyRole_AGENT = 30;
	constexpr int PartyRole_SUB_CUSTODIAN = 31;
	constexpr int PartyRole_BENEFICIARY = 32;
	constexpr int PartyRole_INTERESTED_PARTY = 33;
	constexpr int PartyRole_REGULATORY_BODY = 34;
	constexpr int PartyRole_LIQUIDITY_PROVIDER = 35;
	constexpr int PartyRole_ENTERING_TRADER = 36;
	constexpr int PartyRole_CONTRA_TRADER = 37;
	constexpr int PartyRole_POSITION_ACCOUNT = 38;
	constexpr int Product_AGENCY = 1;
	constexpr int Product_COMMODITY = 2;
	constexpr int Product_CORPORATE = 3;
	constexpr int Product_CURRENCY = 4;
	constexpr int Product_EQUITY = 5;
	constexpr int Product_GOVERNMENT = 6;
	constexpr int Product_INDEX = 7;
	constexpr int Product_LOAN = 8;
	constexpr int Product_MONEYMARKET = 9;
	constexpr int Product_MORTGAGE = 10;
	constexpr int Product_MUNICIPAL = 11;
	constexpr int Product_OTHER = 12;
	constexpr int Product_FINANCING = 13;
	constexpr int QuantityType_SHARES = 1;
	constexpr int QuantityType_BONDS = 2;
	constexpr int QuantityType_CURRENTFACE = 3;
	constexpr int QuantityType_ORIGINALFACE = 4;
	constexpr int QuantityType_CURRENCY = 5;
	constexpr int QuantityType_CONTRACTS = 6;
	constexpr int QuantityType_OTHER = 7;
	constexpr int QuantityType_PAR = 8;
	constexpr char RoundingDirection_ROUND_TO_NEAREST = '0';
	constexpr char RoundingDirection_ROUND_DOWN = '1';
	constexpr char RoundingDirection_ROUND_UP = '2';
	constexpr int DistribPaymentMethod_CREST = 1;
	constexpr int DistribPaymentMethod_NSCC = 2;
	constexpr int DistribPaymentMethod_EUROCLEAR = 3;
	constexpr int DistribPaymentMethod_CLEARSTREAM = 4;
	constexpr int DistribPaymentMethod_CHEQUE = 5;
	constexpr int DistribPaymentMethod_TELEGRAPHIC_TRANSFER = 6;
	constexpr int DistribPaymentMethod_FEDWIRE = 7;
	constexpr int DistribPaymentMethod_DIRECT_CREDIT = 8;
	constexpr int DistribPaymentMethod_ACH_CREDIT = 9;
	constexpr int DistribPaymentMethod_BPAY = 10;
	constexpr int DistribPaymentMethod_HIGH_VALUE_CLEARING_SYSTEM = 11;
	constexpr int DistribPaymentMethod_REINVEST_IN_FUND = 12;
	constexpr char CancellationRights_YES = 'Y';
	constexpr char CancellationRights_NO_EXECUTION_ONLY = 'N';
	constexpr char CancellationRights_NO_WAIVER_AGREEMENT = 'M';
	constexpr char CancellationRights_NO_INSTITUTIONAL = 'O';
	constexpr char MoneyLaunderingStatus_PASSED = 'Y';
	constexpr char MoneyLaunderingStatus_NOT_CHECKED = 'N';
	constexpr char MoneyLaunderingStatus_EXEMPT_BELOW_THE_LIMIT = '1';
	constexpr char MoneyLaunderingStatus_EXEMPT_CLIENT_MONEY_TYPE_EXEMPTION = '2';
	constexpr char MoneyLaunderingStatus_EXEMPT_AUTHORISED_CREDIT_OR_FINANCIAL_INSTITUTION = '3';
	constexpr char ExecPriceType_BID_PRICE = 'B';
	constexpr char ExecPriceType_CREATION_PRICE = 'C';
	constexpr char ExecPriceType_CREATION_PRICE_PLUS_ADJUSTMENT_PERCENT = 'D';
	constexpr char ExecPriceType_CREATION_PRICE_PLUS_ADJUSTMENT_AMOUNT = 'E';
	constexpr char ExecPriceType_OFFER_PRICE = 'O';
	constexpr char ExecPriceType_OFFER_PRICE_MINUS_ADJUSTMENT_PERCENT = 'P';
	constexpr char ExecPriceType_OFFER_PRICE_MINUS_ADJUSTMENT_AMOUNT = 'Q';
	constexpr char ExecPriceType_SINGLE_PRICE = 'S';
	constexpr int TradeReportTransType_NEW = 0;
	constexpr int TradeReportTransType_CANCEL = 1;
	constexpr int TradeReportTransType_REPLACE = 2;
	constexpr int TradeReportTransType_RELEASE = 3;
	constexpr int TradeReportTransType_REVERSE = 4;
	constexpr int PaymentMethod_CREST = 1;
	constexpr int PaymentMethod_NSCC = 2;
	constexpr int PaymentMethod_EUROCLEAR = 3;
	constexpr int PaymentMethod_CLEARSTREAM = 4;
	constexpr int PaymentMethod_CHEQUE = 5;
	constexpr int PaymentMethod_TELEGRAPHIC_TRANSFER = 6;
	constexpr int PaymentMethod_FEDWIRE = 7;
	constexpr int PaymentMethod_DEBIT_CARD = 8;
	constexpr int PaymentMethod_DIRECT_DEBIT = 9;
	constexpr int PaymentMethod_DIRECT_CREDIT = 10;
	constexpr int PaymentMethod_CREDIT_CARD = 11;
	constexpr int PaymentMethod_ACH_DEBIT = 12;
	constexpr int PaymentMethod_ACH_CREDIT = 13;
	constexpr int PaymentMethod_BPAY = 14;
	constexpr int PaymentMethod_HIGH_VALUE_CLEARING_SYSTEM = 15;
	constexpr int TaxAdvantageType_NONE = 0;
	constexpr int TaxAdvantageType_MAXI_ISA = 1;
	constexpr int TaxAdvantageType_TESSA = 2;
	constexpr int TaxAdvantageType_MINI_CASH_ISA = 3;
	constexpr int TaxAdvantageType_MINI_STOCKS_AND_SHARES_ISA = 4;
	constexpr int TaxAdvantageType_MINI_INSURANCE_ISA = 5;
	constexpr int TaxAdvantageType_CURRENT_YEAR_PAYMENT = 6;
	constexpr int TaxAdvantageType_PRIOR_YEAR_PAYMENT = 7;
	constexpr int TaxAdvantageType_ASSET_TRANSFER = 8;
	constexpr int TaxAdvantageType_EMPLOYEE_PRIOR_YEAR = 9;
	constexpr int TaxAdvantageType_OTHER = 999;
	constexpr char FundRenewWaiv_YES = 'Y';
	constexpr char FundRenewWaiv_NO = 'N';
	constexpr char RegistStatus_ACCEPTED = 'A';
	constexpr char RegistStatus_REJECTED = 'R';
	constexpr char RegistStatus_HELD = 'H';
	constexpr char RegistStatus_REMINDER = 'N';
	constexpr int RegistRejReasonCode_INVALID_UNACCEPTABLE_ACCOUNT_TYPE = 1;
	constexpr int RegistRejReasonCode_INVALID_UNACCEPTABLE_TAX_EXEMPT_TYPE = 2;
	constexpr int RegistRejReasonCode_INVALID_UNACCEPTABLE_OWNERSHIP_TYPE = 3;
	constexpr int RegistRejReasonCode_INVALID_UNACCEPTABLE_NO_REG_DETLS = 4;
	constexpr int RegistRejReasonCode_INVALID_UNACCEPTABLE_REG_SEQ_NO = 5;
	constexpr int RegistRejReasonCode_INVALID_UNACCEPTABLE_REG_DTLS = 6;
	constexpr int RegistRejReasonCode_INVALID_UNACCEPTABLE_MAILING_DTLS = 7;
	constexpr int RegistRejReasonCode_INVALID_UNACCEPTABLE_MAILING_INST = 8;
	constexpr int RegistRejReasonCode_INVALID_UNACCEPTABLE_INVESTOR_ID = 9;
	constexpr int RegistRejReasonCode_INVALID_UNACCEPTABLE_INVESTOR_ID_SOURCE = 10;
	constexpr int RegistRejReasonCode_INVALID_UNACCEPTABLE_DATE_OF_BIRTH = 11;
	constexpr int RegistRejReasonCode_INVALID_UNACCEPTABLE_INVESTOR_COUNTRY_OF_RESIDENCE = 12;
	constexpr int RegistRejReasonCode_INVALID_UNACCEPTABLE_NODISTRIBINSTNS = 13;
	constexpr int RegistRejReasonCode_INVALID_UNACCEPTABLE_DISTRIB_PERCENTAGE = 14;
	constexpr int RegistRejReasonCode_INVALID_UNACCEPTABLE_DISTRIB_PAYMENT_METHOD = 15;
	constexpr int RegistRejReasonCode_INVALID_UNACCEPTABLE_CASH_DISTRIB_AGENT_ACCT_NAME = 16;
	constexpr int RegistRejReasonCode_INVALID_UNACCEPTABLE_CASH_DISTRIB_AGENT_CODE = 17;
	constexpr int RegistRejReasonCode_INVALID_UNACCEPTABLE_CASH_DISTRIB_AGENT_ACCT_NUM = 18;
	constexpr int RegistRejReasonCode_OTHER = 99;
	constexpr char RegistTransType_NEW = '0';
	constexpr char RegistTransType_REPLACE = '1';
	constexpr char RegistTransType_CANCEL = '2';
	constexpr char OwnershipType_JOINT_INVESTORS = 'J';
	constexpr char OwnershipType_TENANTS_IN_COMMON = 'T';
	constexpr char OwnershipType_JOINT_TRUSTEES = '2';
	constexpr int ContAmtType_COMMISSION_AMOUNT = 1;
	constexpr int ContAmtType_COMMISSION_PERCENT = 2;
	constexpr int ContAmtType_INITIAL_CHARGE_AMOUNT = 3;
	constexpr int ContAmtType_INITIAL_CHARGE_PERCENT = 4;
	constexpr int ContAmtType_DISCOUNT_AMOUNT = 5;
	constexpr int ContAmtType_DISCOUNT_PERCENT = 6;
	constexpr int ContAmtType_DILUTION_LEVY_AMOUNT = 7;
	constexpr int ContAmtType_DILUTION_LEVY_PERCENT = 8;
	constexpr int ContAmtType_EXIT_CHARGE_AMOUNT = 9;
	constexpr int OwnerType_INDIVIDUAL_INVESTOR = 1;
	constexpr int OwnerType_PUBLIC_COMPANY = 2;
	constexpr int OwnerType_PRIVATE_COMPANY = 3;
	constexpr int OwnerType_INDIVIDUAL_TRUSTEE = 4;
	constexpr int OwnerType_COMPANY_TRUSTEE = 5;
	constexpr int OwnerType_PENSION_PLAN = 6;
	constexpr int OwnerType_CUSTODIAN_UNDER_GIFTS_TO_MINORS_ACT = 7;
	constexpr int OwnerType_TRUSTS = 8;
	constexpr int OwnerType_FIDUCIARIES = 9;
	constexpr int OwnerType_NETWORKING_SUB_ACCOUNT = 10;
	constexpr int OwnerType_NON_PROFIT_ORGANIZATION = 11;
	constexpr int OwnerType_CORPORATE_BODY = 12;
	constexpr int OwnerType_NOMINEE = 13;
	constexpr char OrderCapacity_AGENCY = 'A';
	constexpr char OrderCapacity_PROPRIETARY = 'G';
	constexpr char OrderCapacity_INDIVIDUAL = 'I';
	constexpr char OrderCapacity_PRINCIPAL = 'P';
	constexpr char OrderCapacity_RISKLESS_PRINCIPAL = 'R';
	constexpr char OrderCapacity_AGENT_FOR_OTHER_MEMBER = 'W';
	constexpr char MassCancelRequestType_CANCEL_ORDERS_FOR_A_SECURITY = '1';
	constexpr char MassCancelRequestType_CANCEL_ORDERS_FOR_AN_UNDERLYING_SECURITY = '2';
	constexpr char MassCancelRequestType_CANCEL_ORDERS_FOR_A_PRODUCT = '3';
	constexpr char MassCancelRequestType_CANCEL_ORDERS_FOR_A_CFICODE = '4';
	constexpr char MassCancelRequestType_CANCEL_ORDERS_FOR_A_SECURITYTYPE = '5';
	constexpr char MassCancelRequestType_CANCEL_ORDERS_FOR_A_TRADING_SESSION = '6';
	constexpr char MassCancelRequestType_CANCEL_ALL_ORDERS = '7';
	constexpr char MassCancelResponse_CANCEL_REQUEST_REJECTED = '0';
	constexpr char MassCancelResponse_CANCEL_ORDERS_FOR_A_SECURITY = '1';
	constexpr char MassCancelResponse_CANCEL_ORDERS_FOR_AN_UNDERLYING_SECURITY = '2';
	constexpr char MassCancelResponse_CANCEL_ORDERS_FOR_A_PRODUCT = '3';
	constexpr char MassCancelResponse_CANCEL_ORDERS_FOR_A_CFICODE = '4';
	constexpr char MassCancelResponse_CANCEL_ORDERS_FOR_A_SECURITYTYPE = '5';
	constexpr char MassCancelResponse_CANCEL_ORDERS_FOR_A_TRADING_SESSION = '6';
	constexpr char MassCancelResponse_CANCEL_ALL_ORDERS = '7';
	constexpr char MassCancelRejectReason_MASS_CANCEL_NOT_SUPPORTED = '0';
	constexpr char MassCancelRejectReason_INVALID_OR_UNKNOWN_SECURITY = '1';
	constexpr char MassCancelRejectReason_INVALID_OR_UNKNOWN_UNDERLYING = '2';
	constexpr char MassCancelRejectReason_INVALID_OR_UNKNOWN_PRODUCT = '3';
	constexpr char MassCancelRejectReason_INVALID_OR_UNKNOWN_CFICODE = '4';
	constexpr char MassCancelRejectReason_INVALID_OR_UNKNOWN_SECURITY_TYPE = '5';
	constexpr char MassCancelRejectReason_INVALID_OR_UNKNOWN_TRADING_SESSION = '6';
	constexpr char MassCancelRejectReason_OTHER = '99';
	constexpr int QuoteType_INDICATIVE = 0;
	constexpr int QuoteType_TRADEABLE = 1;
	constexpr int QuoteType_RESTRICTED_TRADEABLE = 2;
	constexpr int QuoteType_COUNTER = 3;
	constexpr char CashMargin_CASH = '1';
	constexpr char CashMargin_MARGIN_OPEN = '2';
	constexpr char CashMargin_MARGIN_CLOSE = '3';
	constexpr int CrossType_CROSS_TRADE_WHICH_IS_EXECUTED_COMPLETELY_OR_NOT = 1;
	constexpr int CrossType_CROSS_TRADE_WHICH_IS_EXECUTED_PARTIALLY_AND_THE_REST_IS_CANCELLED = 2;
	constexpr int CrossType_CROSS_TRADE_WHICH_IS_PARTIALLY_EXECUTED_WITH_THE_UNFILLED_PORTIONS_REMAINING_ACTIVE = 3;
	constexpr int CrossType_CROSS_TRADE_IS_EXECUTED_WITH_EXISTING_ORDERS_WITH_THE_SAME_PRICE = 4;
	constexpr int CrossPrioritization_NONE = 0;
	constexpr int CrossPrioritization_BUY_SIDE_IS_PRIORITIZED = 1;
	constexpr int CrossPrioritization_SELL_SIDE_IS_PRIORITIZED = 2;
	constexpr int SecurityListRequestType_SYMBOL = 0;
	constexpr int SecurityListRequestType_SECURITYTYPE_AND_OR_CFICODE = 1;
	constexpr int SecurityListRequestType_PRODUCT = 2;
	constexpr int SecurityListRequestType_TRADINGSESSIONID = 3;
	constexpr int SecurityListRequestType_ALL_SECURITIES = 4;
	constexpr int SecurityRequestResult_VALID_REQUEST = 0;
	constexpr int SecurityRequestResult_INVALID_OR_UNSUPPORTED_REQUEST = 1;
	constexpr int SecurityRequestResult_NO_INSTRUMENTS_FOUND_THAT_MATCH_SELECTION_CRITERIA = 2;
	constexpr int SecurityRequestResult_NOT_AUTHORIZED_TO_RETRIEVE_INSTRUMENT_DATA = 3;
	constexpr int SecurityRequestResult_INSTRUMENT_DATA_TEMPORARILY_UNAVAILABLE = 4;
	constexpr int SecurityRequestResult_REQUEST_FOR_INSTRUMENT_DATA_NOT_SUPPORTED = 5;
	constexpr int MultiLegRptTypeReq_REPORT_BY_MULITLEG_SECURITY_ONLY = 0;
	constexpr int MultiLegRptTypeReq_REPORT_BY_MULTILEG_SECURITY_AND_BY_INSTRUMENT_LEGS_BELONGING_TO_THE_MULTILEG_SECURITY = 1;
	constexpr int MultiLegRptTypeReq_REPORT_BY_INSTRUMENT_LEGS_BELONGING_TO_THE_MULTILEG_SECURITY_ONLY = 2;
	constexpr int TradSesStatusRejReason_UNKNOWN_OR_INVALID_TRADINGSESSIONID = 1;
	constexpr int TradeRequestType_ALL_TRADES = 0;
	constexpr int TradeRequestType_MATCHED_TRADES_MATCHING_CRITERIA_PROVIDED_ON_REQUEST = 1;
	constexpr int TradeRequestType_UNMATCHED_TRADES_THAT_MATCH_CRITERIA = 2;
	constexpr int TradeRequestType_UNREPORTED_TRADES_THAT_MATCH_CRITERIA = 3;
	constexpr int TradeRequestType_ADVISORIES_THAT_MATCH_CRITERIA = 4;
	constexpr char MatchStatus_COMPARED_MATCHED_OR_AFFIRMED = '0';
	constexpr char MatchStatus_UNCOMPARED_UNMATCHED_OR_UNAFFIRMED = '1';
	constexpr char MatchStatus_ADVISORY_OR_ALERT = '2';
	constexpr int ClearingInstruction_PROCESS_NORMALLY = 0;
	constexpr int ClearingInstruction_EXCLUDE_FROM_ALL_NETTING = 1;
	constexpr int ClearingInstruction_BILATERAL_NETTING_ONLY = 2;
	constexpr int ClearingInstruction_EX_CLEARING = 3;
	constexpr int ClearingInstruction_SPECIAL_TRADE = 4;
	constexpr int ClearingInstruction_MULTILATERAL_NETTING = 5;
	constexpr int ClearingInstruction_CLEAR_AGAINST_CENTRAL_COUNTERPARTY = 6;
	constexpr int ClearingInstruction_EXCLUDE_FROM_CENTRAL_COUNTERPARTY = 7;
	constexpr int ClearingInstruction_MANUAL_MODE = 8;
	constexpr int ClearingInstruction_AUTOMATIC_POSTING_MODE = 9;
	constexpr int ClearingInstruction_AUTOMATIC_GIVE_UP_MODE = 10;
	constexpr int ClearingInstruction_QUALIFIED_SERVICE_REPRESENTATIVE = 11;
	constexpr int ClearingInstruction_CUSTOMER_TRADE = 12;
	constexpr int ClearingInstruction_SELF_CLEARING = 13;
	constexpr int AccountType_ACCOUNT_IS_CARRIED_ON_CUSTOMER_SIDE_OF_BOOKS = 1;
	constexpr int AccountType_ACCOUNT_IS_CARRIED_ON_NON_CUSTOMER_SIDE_OF_BOOKS = 2;
	constexpr int AccountType_HOUSE_TRADER = 3;
	constexpr int AccountType_FLOOR_TRADER = 4;
	constexpr int AccountType_ACCOUNT_IS_CARRIED_ON_NON_CUSTOMER_SIDE_OF_BOOKS_AND_IS_CROSS_MARGINED = 6;
	constexpr int AccountType_ACCOUNT_IS_HOUSE_TRADER_AND_IS_CROSS_MARGINED = 7;
	constexpr int AccountType_JOINT_BACKOFFICE_ACCOUNT = 8;
	constexpr int CustOrderCapacity_MEMBER_TRADING_FOR_THEIR_OWN_ACCOUNT = 1;
	constexpr int CustOrderCapacity_CLEARING_FIRM_TRADING_FOR_ITS_PROPRIETARY_ACCOUNT = 2;
	constexpr int CustOrderCapacity_MEMBER_TRADING_FOR_ANOTHER_MEMBER = 3;
	constexpr int CustOrderCapacity_ALL_OTHER = 4;
	constexpr int MassStatusReqType_STATUS_FOR_ORDERS_FOR_A_SECURITY = 1;
	constexpr int MassStatusReqType_STATUS_FOR_ORDERS_FOR_AN_UNDERLYING_SECURITY = 2;
	constexpr int MassStatusReqType_STATUS_FOR_ORDERS_FOR_A_PRODUCT = 3;
	constexpr int MassStatusReqType_STATUS_FOR_ORDERS_FOR_A_CFICODE = 4;
	constexpr int MassStatusReqType_STATUS_FOR_ORDERS_FOR_A_SECURITYTYPE = 5;
	constexpr int MassStatusReqType_STATUS_FOR_ORDERS_FOR_A_TRADING_SESSION = 6;
	constexpr int MassStatusReqType_STATUS_FOR_ALL_ORDERS = 7;
	constexpr int MassStatusReqType_STATUS_FOR_ORDERS_FOR_A_PARTYID = 8;
	constexpr char DayBookingInst_CAN_TRIGGER_BOOKING_WITHOUT_REFERENCE_TO_THE_ORDER_INITIATOR = '0';
	constexpr char DayBookingInst_SPEAK_WITH_ORDER_INITIATOR_BEFORE_BOOKING = '1';
	constexpr char DayBookingInst_ACCUMULATE = '2';
	constexpr char BookingUnit_EACH_PARTIAL_EXECUTION_IS_A_BOOKABLE_UNIT = '0';
	constexpr char BookingUnit_AGGREGATE_PARTIAL_EXECUTIONS_ON_THIS_ORDER_AND_BOOK_ONE_TRADE_PER_ORDER = '1';
	constexpr char BookingUnit_AGGREGATE_EXECUTIONS_FOR_THIS_SYMBOL_SIDE_AND_SETTLEMENT_DATE = '2';
	constexpr char PreallocMethod_PRO_RATA = '0';
	constexpr char PreallocMethod_DO_NOT_PRO_RATA = '1';
	constexpr int AllocType_CALCULATED = 1;
	constexpr int AllocType_PRELIMINARY = 2;
	constexpr int AllocType_READY_TO_BOOK_SINGLE_ORDER = 5;
	constexpr int AllocType_WAREHOUSE_INSTRUCTION = 7;
	constexpr int AllocType_REQUEST_TO_INTERMEDIARY = 8;
	constexpr int PriorityIndicator_PRIORITY_UNCHANGED = 0;
	constexpr int PriorityIndicator_LOST_PRIORITY_AS_RESULT_OF_ORDER_CHANGE = 1;
	constexpr int QuoteRequestRejectReason_UNKNOWN_SYMBOL = 1;
	constexpr int QuoteRequestRejectReason_EXCHANGE_CLOSED = 2;
	constexpr int QuoteRequestRejectReason_QUOTE_REQUEST_EXCEEDS_LIMIT = 3;
	constexpr int QuoteRequestRejectReason_TOO_LATE_TO_ENTER = 4;
	constexpr int QuoteRequestRejectReason_INVALID_PRICE = 5;
	constexpr int QuoteRequestRejectReason_NOT_AUTHORIZED_TO_REQUEST_QUOTE = 6;
	constexpr int QuoteRequestRejectReason_NO_MATCH_FOR_INQUIRY = 7;
	constexpr int QuoteRequestRejectReason_NO_MARKET_FOR_INSTRUMENT = 8;
	constexpr int QuoteRequestRejectReason_NO_INVENTORY = 9;
	constexpr int QuoteRequestRejectReason_PASS = 10;
	constexpr int QuoteRequestRejectReason_OTHER = 99;
	constexpr int AcctIDSource_BIC = 1;
	constexpr int AcctIDSource_SID_CODE = 2;
	constexpr int AcctIDSource_TFM = 3;
	constexpr int AcctIDSource_OMGEO = 4;
	constexpr int AcctIDSource_DTCC_CODE = 5;
	constexpr int AcctIDSource_OTHER = 99;
	constexpr int ConfirmStatus_RECEIVED = 1;
	constexpr int ConfirmStatus_MISMATCHED_ACCOUNT = 2;
	constexpr int ConfirmStatus_MISSING_SETTLEMENT_INSTRUCTIONS = 3;
	constexpr int ConfirmStatus_CONFIRMED = 4;
	constexpr int ConfirmStatus_REQUEST_REJECTED = 5;
	constexpr int ConfirmTransType_NEW = 0;
	constexpr int ConfirmTransType_REPLACE = 1;
	constexpr int ConfirmTransType_CANCEL = 2;
	constexpr int DeliveryForm_BOOKENTRY = 1;
	constexpr int DeliveryForm_BEARER = 2;
	constexpr int LegSwapType_PAR_FOR_PAR = 1;
	constexpr int LegSwapType_MODIFIED_DURATION = 2;
	constexpr int LegSwapType_RISK = 4;
	constexpr int LegSwapType_PROCEEDS = 5;
	constexpr int QuotePriceType_PERCENT = 1;
	constexpr int QuotePriceType_PER_SHARE = 2;
	constexpr int QuotePriceType_FIXED_AMOUNT = 3;
	constexpr int QuotePriceType_DISCOUNT = 4;
	constexpr int QuotePriceType_PREMIUM = 5;
	constexpr int QuotePriceType_BASIS_POINTS_RELATIVE_TO_BENCHMARK = 6;
	constexpr int QuotePriceType_TED_PRICE = 7;
	constexpr int QuotePriceType_TED_YIELD = 8;
	constexpr int QuotePriceType_YIELD_SPREAD = 9;
	constexpr int QuotePriceType_YIELD = 10;
	constexpr int QuoteRespType_HIT_LIFT = 1;
	constexpr int QuoteRespType_COUNTER = 2;
	constexpr int QuoteRespType_EXPIRED = 3;
	constexpr int QuoteRespType_COVER = 4;
	constexpr int QuoteRespType_DONE_AWAY = 5;
	constexpr int QuoteRespType_PASS = 6;
	constexpr int PosQtyStatus_SUBMITTED = 0;
	constexpr int PosQtyStatus_ACCEPTED = 1;
	constexpr int PosQtyStatus_REJECTED = 2;
	constexpr int PosTransType_EXERCISE = 1;
	constexpr int PosTransType_DO_NOT_EXERCISE = 2;
	constexpr int PosTransType_POSITION_ADJUSTMENT = 3;
	constexpr int PosTransType_POSITION_CHANGE_SUBMISSION_MARGIN_DISPOSITION = 4;
	constexpr int PosTransType_PLEDGE = 5;
	constexpr int PosMaintAction_NEW = 1;
	constexpr int PosMaintAction_REPLACE = 2;
	constexpr int PosMaintAction_CANCEL = 3;
	constexpr int AdjustmentType_PROCESS_REQUEST_AS_MARGIN_DISPOSITION = 0;
	constexpr int AdjustmentType_DELTA_PLUS = 1;
	constexpr int AdjustmentType_DELTA_MINUS = 2;
	constexpr int AdjustmentType_FINAL = 3;
	constexpr int PosMaintStatus_ACCEPTED = 0;
	constexpr int PosMaintStatus_ACCEPTED_WITH_WARNINGS = 1;
	constexpr int PosMaintStatus_REJECTED = 2;
	constexpr int PosMaintStatus_COMPLETED = 3;
	constexpr int PosMaintStatus_COMPLETED_WITH_WARNINGS = 4;
	constexpr int PosMaintResult_SUCCESSFUL_COMPLETION_NO_WARNINGS_OR_ERRORS = 0;
	constexpr int PosMaintResult_REJECTED = 1;
	constexpr int PosMaintResult_OTHER = 99;
	constexpr int PosReqType_POSITIONS = 0;
	constexpr int PosReqType_TRADES = 1;
	constexpr int PosReqType_EXERCISES = 2;
	constexpr int PosReqType_ASSIGNMENTS = 3;
	constexpr int ResponseTransportType_INBAND = 0;
	constexpr int ResponseTransportType_OUT_OF_BAND = 1;
	constexpr int PosReqResult_VALID_REQUEST = 0;
	constexpr int PosReqResult_INVALID_OR_UNSUPPORTED_REQUEST = 1;
	constexpr int PosReqResult_NO_POSITIONS_FOUND_THAT_MATCH_CRITERIA = 2;
	constexpr int PosReqResult_NOT_AUTHORIZED_TO_REQUEST_POSITIONS = 3;
	constexpr int PosReqResult_REQUEST_FOR_POSITION_NOT_SUPPORTED = 4;
	constexpr int PosReqResult_OTHER = 99;
	constexpr int PosReqStatus_COMPLETED = 0;
	constexpr int PosReqStatus_COMPLETED_WITH_WARNINGS = 1;
	constexpr int PosReqStatus_REJECTED = 2;
	constexpr int SettlPriceType_FINAL = 1;
	constexpr int SettlPriceType_THEORETICAL = 2;
	constexpr char AssignmentMethod_RANDOM = 'R';
	constexpr char AssignmentMethod_PRORATA = 'P';
	constexpr char ExerciseMethod_AUTOMATIC = 'A';
	constexpr char ExerciseMethod_MANUAL = 'M';
	constexpr int TradeRequestResult_SUCCESSFUL = 0;
	constexpr int TradeRequestResult_INVALID_OR_UNKNOWN_INSTRUMENT = 1;
	constexpr int TradeRequestResult_INVALID_TYPE_OF_TRADE_REQUESTED = 2;
	constexpr int TradeRequestResult_INVALID_PARTIES = 3;
	constexpr int TradeRequestResult_INVALID_TRANSPORT_TYPE_REQUESTED = 4;
	constexpr int TradeRequestResult_INVALID_DESTINATION_REQUESTED = 5;
	constexpr int TradeRequestResult_TRADEREQUESTTYPE_NOT_SUPPORTED = 8;
	constexpr int TradeRequestResult_UNAUTHORIZED_FOR_TRADE_CAPTURE_REPORT_REQUEST = 9;
	constexpr int TradeRequestResult_OTHER = 99;
	constexpr int TradeRequestStatus_ACCEPTED = 0;
	constexpr int TradeRequestStatus_COMPLETED = 1;
	constexpr int TradeRequestStatus_REJECTED = 2;
	constexpr int TradeReportRejectReason_SUCCESSFUL = 0;
	constexpr int TradeReportRejectReason_INVALID_PARTY_INFORMATION = 1;
	constexpr int TradeReportRejectReason_UNKNOWN_INSTRUMENT = 2;
	constexpr int TradeReportRejectReason_UNAUTHORIZED_TO_REPORT_TRADES = 3;
	constexpr int TradeReportRejectReason_INVALID_TRADE_TYPE = 4;
	constexpr int TradeReportRejectReason_OTHER = 99;
	constexpr int SideMultiLegReportingType_SINGLE_SECURITY = 1;
	constexpr int SideMultiLegReportingType_INDIVIDUAL_LEG_OF_A_MULTI_LEG_SECURITY = 2;
	constexpr int SideMultiLegReportingType_MULTI_LEG_SECURITY = 3;
	constexpr int TrdRegTimestampType_EXECUTION_TIME = 1;
	constexpr int TrdRegTimestampType_TIME_IN = 2;
	constexpr int TrdRegTimestampType_TIME_OUT = 3;
	constexpr int TrdRegTimestampType_BROKER_RECEIPT = 4;
	constexpr int TrdRegTimestampType_BROKER_EXECUTION = 5;
	constexpr int ConfirmType_STATUS = 1;
	constexpr int ConfirmType_CONFIRMATION = 2;
	constexpr int ConfirmType_CONFIRMATION_REQUEST_REJECTED = 3;
	constexpr int ConfirmRejReason_MISMATCHED_ACCOUNT = 1;
	constexpr int ConfirmRejReason_MISSING_SETTLEMENT_INSTRUCTIONS = 2;
	constexpr int ConfirmRejReason_OTHER = 99;
	constexpr int BookingType_REGULAR_BOOKING = 0;
	constexpr int BookingType_CFD = 1;
	constexpr int BookingType_TOTAL_RETURN_SWAP = 2;
	constexpr int AllocSettlInstType_USE_DEFAULT_INSTRUCTIONS = 0;
	constexpr int AllocSettlInstType_DERIVE_FROM_PARAMETERS_PROVIDED = 1;
	constexpr int AllocSettlInstType_FULL_DETAILS_PROVIDED = 2;
	constexpr int AllocSettlInstType_SSI_DB_IDS_PROVIDED = 3;
	constexpr int AllocSettlInstType_PHONE_FOR_INSTRUCTIONS = 4;
	constexpr char DlvyInstType_SECURITIES = 'S';
	constexpr char DlvyInstType_CASH = 'C';
	constexpr int TerminationType_OVERNIGHT = 1;
	constexpr int TerminationType_TERM = 2;
	constexpr int TerminationType_FLEXIBLE = 3;
	constexpr int TerminationType_OPEN = 4;
	constexpr int SettlInstReqRejCode_UNABLE_TO_PROCESS_REQUEST = 0;
	constexpr int SettlInstReqRejCode_UNKNOWN_ACCOUNT = 1;
	constexpr int SettlInstReqRejCode_NO_MATCHING_SETTLEMENT_INSTRUCTIONS_FOUND = 2;
	constexpr int SettlInstReqRejCode_OTHER = 99;
	constexpr int AllocReportType_SELLSIDE_CALCULATED_USING_PRELIMINARY = 3;
	constexpr int AllocReportType_SELLSIDE_CALCULATED_WITHOUT_PRELIMINARY = 4;
	constexpr int AllocReportType_WAREHOUSE_RECAP = 5;
	constexpr int AllocReportType_REQUEST_TO_INTERMEDIARY = 8;
	constexpr int AllocCancReplaceReason_ORIGINAL_DETAILS_INCOMPLETE_INCORRECT = 1;
	constexpr int AllocCancReplaceReason_CHANGE_IN_UNDERLYING_ORDER_DETAILS = 2;
	constexpr int AllocAccountType_ACCOUNT_IS_CARRIED_ON_CUSTOMER_SIDE_OF_BOOKS = 1;
	constexpr int AllocAccountType_ACCOUNT_IS_CARRIED_ON_NON_CUSTOMER_SIDE_OF_BOOKS = 2;
	constexpr int AllocAccountType_HOUSE_TRADER = 3;
	constexpr int AllocAccountType_FLOOR_TRADER = 4;
	constexpr int AllocAccountType_ACCOUNT_IS_CARRIED_ON_NON_CUSTOMER_SIDE_OF_BOOKS_AND_IS_CROSS_MARGINED = 6;
	constexpr int AllocAccountType_ACCOUNT_IS_HOUSE_TRADER_AND_IS_CROSS_MARGINED = 7;
	constexpr int AllocAccountType_JOINT_BACKOFFICE_ACCOUNT = 8;
	constexpr int AllocIntermedReqType_PENDING_ACCEPT = 1;
	constexpr int AllocIntermedReqType_PENDING_RELEASE = 2;
	constexpr int AllocIntermedReqType_PENDING_REVERSAL = 3;
	constexpr int AllocIntermedReqType_ACCEPT = 4;
	constexpr int AllocIntermedReqType_BLOCK_LEVEL_REJECT = 5;
	constexpr int AllocIntermedReqType_ACCOUNT_LEVEL_REJECT = 6;
	constexpr int ApplQueueResolution_NO_ACTION_TAKEN = 0;
	constexpr int ApplQueueResolution_QUEUE_FLUSHED = 1;
	constexpr int ApplQueueResolution_OVERLAY_LAST = 2;
	constexpr int ApplQueueResolution_END_SESSION = 3;
	constexpr int ApplQueueAction_NO_ACTION_TAKEN = 0;
	constexpr int ApplQueueAction_QUEUE_FLUSHED = 1;
	constexpr int ApplQueueAction_OVERLAY_LAST = 2;
	constexpr int ApplQueueAction_END_SESSION = 3;
	constexpr int AvgPxIndicator_NO_AVERAGE_PRICING = 0;
	constexpr int AvgPxIndicator_TRADE_IS_PART_OF_AN_AVERAGE_PRICE_GROUP_IDENTIFIED_BY_THE_TRADELINKID = 1;
	constexpr int AvgPxIndicator_LAST_TRADE_IN_THE_AVERAGE_PRICE_GROUP_IDENTIFIED_BY_THE_TRADELINKID = 2;
	constexpr int TradeAllocIndicator_ALLOCATION_NOT_REQUIRED = 0;
	constexpr int TradeAllocIndicator_ALLOCATION_REQUIRED = 1;
	constexpr int TradeAllocIndicator_USE_ALLOCATION_PROVIDED_WITH_THE_TRADE = 2;
	constexpr int ExpirationCycle_EXPIRE_ON_TRADING_SESSION_CLOSE = 0;
	constexpr int ExpirationCycle_EXPIRE_ON_TRADING_SESSION_OPEN = 1;
	constexpr int TrdType_REGULAR_TRADE = 0;
	constexpr int TrdType_BLOCK_TRADE = 1;
	constexpr int TrdType_EFP = 2;
	constexpr int TrdType_TRANSFER = 3;
	constexpr int TrdType_LATE_TRADE = 4;
	constexpr int TrdType_T_TRADE = 5;
	constexpr int TrdType_WEIGHTED_AVERAGE_PRICE_TRADE = 6;
	constexpr int TrdType_BUNCHED_TRADE = 7;
	constexpr int TrdType_LATE_BUNCHED_TRADE = 8;
	constexpr int TrdType_PRIOR_REFERENCE_PRICE_TRADE = 9;
	constexpr int TrdType_AFTER_HOURS_TRADE = 10;
	constexpr int PegMoveType_FLOATING = 0;
	constexpr int PegMoveType_FIXED = 1;
	constexpr int PegOffsetType_PRICE = 0;
	constexpr int PegOffsetType_BASIS_POINTS = 1;
	constexpr int PegOffsetType_TICKS = 2;
	constexpr int PegOffsetType_PRICE_TIER_LEVEL = 3;
	constexpr int PegLimitType_OR_BETTER = 0;
	constexpr int PegLimitType_STRICT = 1;
	constexpr int PegLimitType_OR_WORSE = 2;
	constexpr int PegRoundDirection_MORE_AGGRESSIVE = 1;
	constexpr int PegRoundDirection_MORE_PASSIVE = 2;
	constexpr int PegScope_LOCAL = 1;
	constexpr int PegScope_NATIONAL = 2;
	constexpr int PegScope_GLOBAL = 3;
	constexpr int PegScope_NATIONAL_EXCLUDING_LOCAL = 4;
	constexpr int DiscretionMoveType_FLOATING = 0;
	constexpr int DiscretionMoveType_FIXED = 1;
	constexpr int DiscretionOffsetType_PRICE = 0;
	constexpr int DiscretionOffsetType_BASIS_POINTS = 1;
	constexpr int DiscretionOffsetType_TICKS = 2;
	constexpr int DiscretionOffsetType_PRICE_TIER_LEVEL = 3;
	constexpr int DiscretionLimitType_OR_BETTER = 0;
	constexpr int DiscretionLimitType_STRICT = 1;
	constexpr int DiscretionLimitType_OR_WORSE = 2;
	constexpr int DiscretionRoundDirection_MORE_AGGRESSIVE = 1;
	constexpr int DiscretionRoundDirection_MORE_PASSIVE = 2;
	constexpr int DiscretionScope_LOCAL = 1;
	constexpr int DiscretionScope_NATIONAL = 2;
	constexpr int DiscretionScope_GLOBAL = 3;
	constexpr int DiscretionScope_NATIONAL_EXCLUDING_LOCAL = 4;
	constexpr int LastLiquidityInd_ADDED_LIQUIDITY = 1;
	constexpr int LastLiquidityInd_REMOVED_LIQUIDITY = 2;
	constexpr int LastLiquidityInd_LIQUIDITY_ROUTED_OUT = 3;
	constexpr int ShortSaleReason_DEALER_SOLD_SHORT = 0;
	constexpr int ShortSaleReason_DEALER_SOLD_SHORT_EXEMPT = 1;
	constexpr int ShortSaleReason_SELLING_CUSTOMER_SOLD_SHORT = 2;
	constexpr int ShortSaleReason_SELLING_CUSTOMER_SOLD_SHORT_EXEMPT = 3;
	constexpr int ShortSaleReason_QUALIFED_SERVICE_REPRESENTATIVE_OR_AUTOMATIC_GIVEUP_CONTRA_SIDE_SOLD_SHORT = 4;
	constexpr int ShortSaleReason_QSR_OR_AGU_CONTRA_SIDE_SOLD_SHORT_EXEMPT = 5;
	constexpr int QtyType_UNITS = 0;
	constexpr int QtyType_CONTRACTS = 1;
	constexpr int TradeReportType_SUBMIT = 0;
	constexpr int TradeReportType_ALLEGED = 1;
	constexpr int TradeReportType_ACCEPT = 2;
	constexpr int TradeReportType_DECLINE = 3;
	constexpr int TradeReportType_ADDENDUM = 4;
	constexpr int TradeReportType_NO_WAS = 5;
	constexpr int TradeReportType_TRADE_REPORT_CANCEL = 6;
	constexpr int TradeReportType_LOCKED_IN_TRADE_BREAK = 7;
	constexpr int AllocNoOrdersType_NOT_SPECIFIED = 0;
	constexpr int AllocNoOrdersType_EXPLICIT_LIST_PROVIDED = 1;
	constexpr int EventType_PUT = 1;
	constexpr int EventType_CALL = 2;
	constexpr int EventType_TENDER = 3;
	constexpr int EventType_SINKING_FUND_CALL = 4;
	constexpr int EventType_OTHER = 99;
	constexpr int InstrAttribType_FLAT = 1;
	constexpr int InstrAttribType_ZERO_COUPON = 2;
	constexpr int InstrAttribType_INTEREST_BEARING = 3;
	constexpr int InstrAttribType_NO_PERIODIC_PAYMENTS = 4;
	constexpr int InstrAttribType_VARIABLE_RATE = 5;
	constexpr int InstrAttribType_LESS_FEE_FOR_PUT = 6;
	constexpr int InstrAttribType_STEPPED_COUPON = 7;
	constexpr int InstrAttribType_COUPON_PERIOD = 8;
	constexpr int InstrAttribType_WHEN_AND_IF_ISSUED = 9;
	constexpr int InstrAttribType_ORIGINAL_ISSUE_DISCOUNT = 10;
	constexpr int InstrAttribType_CALLABLE_PUTTABLE = 11;
	constexpr int InstrAttribType_ESCROWED_TO_MATURITY = 12;
	constexpr int InstrAttribType_ESCROWED_TO_REDEMPTION_DATE = 13;
	constexpr int InstrAttribType_PRE_REFUNDED = 14;
	constexpr int InstrAttribType_IN_DEFAULT = 15;
	constexpr int InstrAttribType_UNRATED = 16;
	constexpr int InstrAttribType_TAXABLE = 17;
	constexpr int InstrAttribType_INDEXED = 18;
	constexpr int InstrAttribType_SUBJECT_TO_ALTERNATIVE_MINIMUM_TAX = 19;
	constexpr int InstrAttribType_ORIGINAL_ISSUE_DISCOUNT_PRICE = 20;
	constexpr int InstrAttribType_CALLABLE_BELOW_MATURITY_VALUE = 21;
	constexpr int InstrAttribType_CALLABLE_WITHOUT_NOTICE_BY_MAIL_TO_HOLDER_UNLESS_REGISTERED = 22;
	constexpr int InstrAttribType_TEXT = 99;
	constexpr int MiscFeeBasis_ABSOLUTE = 0;
	constexpr int MiscFeeBasis_PER_UNIT = 1;
	constexpr int MiscFeeBasis_PERCENTAGE = 2;
	constexpr int CollAsgnReason_INITIAL = 0;
	constexpr int CollAsgnReason_SCHEDULED = 1;
	constexpr int CollAsgnReason_TIME_WARNING = 2;
	constexpr int CollAsgnReason_MARGIN_DEFICIENCY = 3;
	constexpr int CollAsgnReason_MARGIN_EXCESS = 4;
	constexpr int CollAsgnReason_FORWARD_COLLATERAL_DEMAND = 5;
	constexpr int CollAsgnReason_EVENT_OF_DEFAULT = 6;
	constexpr int CollAsgnReason_ADVERSE_TAX_EVENT = 7;
	constexpr int CollInquiryQualifier_TRADEDATE = 0;
	constexpr int CollInquiryQualifier_GC_INSTRUMENT = 1;
	constexpr int CollInquiryQualifier_COLLATERALINSTRUMENT = 2;
	constexpr int CollInquiryQualifier_SUBSTITUTION_ELIGIBLE = 3;
	constexpr int CollInquiryQualifier_NOT_ASSIGNED = 4;
	constexpr int CollInquiryQualifier_PARTIALLY_ASSIGNED = 5;
	constexpr int CollInquiryQualifier_FULLY_ASSIGNED = 6;
	constexpr int CollInquiryQualifier_OUTSTANDING_TRADES = 7;
	constexpr int CollAsgnTransType_NEW = 0;
	constexpr int CollAsgnTransType_REPLACE = 1;
	constexpr int CollAsgnTransType_CANCEL = 2;
	constexpr int CollAsgnTransType_RELEASE = 3;
	constexpr int CollAsgnTransType_REVERSE = 4;
	constexpr int CollAsgnRespType_RECEIVED = 0;
	constexpr int CollAsgnRespType_ACCEPTED = 1;
	constexpr int CollAsgnRespType_DECLINED = 2;
	constexpr int CollAsgnRespType_REJECTED = 3;
	constexpr int CollAsgnRejectReason_UNKNOWN_DEAL = 0;
	constexpr int CollAsgnRejectReason_UNKNOWN_OR_INVALID_INSTRUMENT = 1;
	constexpr int CollAsgnRejectReason_UNAUTHORIZED_TRANSACTION = 2;
	constexpr int CollAsgnRejectReason_INSUFFICIENT_COLLATERAL = 3;
	constexpr int CollAsgnRejectReason_INVALID_TYPE_OF_COLLATERAL = 4;
	constexpr int CollAsgnRejectReason_EXCESSIVE_SUBSTITUTION = 5;
	constexpr int CollAsgnRejectReason_OTHER = 99;
	constexpr int CollStatus_UNASSIGNED = 0;
	constexpr int CollStatus_PARTIALLY_ASSIGNED = 1;
	constexpr int CollStatus_ASSIGNMENT_PROPOSED = 2;
	constexpr int CollStatus_ASSIGNED = 3;
	constexpr int CollStatus_CHALLENGED = 4;
	constexpr int DeliveryType_VERSUS_PAYMENT = 0;
	constexpr int DeliveryType_FREE = 1;
	constexpr int DeliveryType_TRI_PARTY = 2;
	constexpr int DeliveryType_HOLD_IN_CUSTODY = 3;
	constexpr int UserRequestType_LOGONUSER = 1;
	constexpr int UserRequestType_LOGOFFUSER = 2;
	constexpr int UserRequestType_CHANGEPASSWORDFORUSER = 3;
	constexpr int UserRequestType_REQUEST_INDIVIDUAL_USER_STATUS = 4;
	constexpr int UserStatus_LOGGED_IN = 1;
	constexpr int UserStatus_NOT_LOGGED_IN = 2;
	constexpr int UserStatus_USER_NOT_RECOGNISED = 3;
	constexpr int UserStatus_PASSWORD_INCORRECT = 4;
	constexpr int UserStatus_PASSWORD_CHANGED = 5;
	constexpr int UserStatus_OTHER = 6;
	constexpr int StatusValue_CONNECTED = 1;
	constexpr int StatusValue_NOT_CONNECTED_DOWN_EXPECTED_UP = 2;
	constexpr int StatusValue_NOT_CONNECTED_DOWN_EXPECTED_DOWN = 3;
	constexpr int StatusValue_IN_PROCESS = 4;
	constexpr int NetworkRequestType_SNAPSHOT = 1;
	constexpr int NetworkRequestType_SUBSCRIBE = 2;
	constexpr int NetworkRequestType_STOP_SUBSCRIBING = 4;
	constexpr int NetworkRequestType_LEVEL_OF_DETAIL = 8;
	constexpr int NetworkStatusResponseType_FULL = 1;
	constexpr int NetworkStatusResponseType_INCREMENTAL_UPDATE = 2;
	constexpr int TrdRptStatus_ACCEPTED = 0;
	constexpr int TrdRptStatus_REJECTED = 1;
	constexpr int AffirmStatus_RECEIVED = 1;
	constexpr int AffirmStatus_CONFIRM_REJECTED = 2;
	constexpr int AffirmStatus_AFFIRMED = 3;
	constexpr int CollAction_RETAIN = 0;
	constexpr int CollAction_ADD = 1;
	constexpr int CollAction_REMOVE = 2;
	constexpr int CollInquiryStatus_ACCEPTED = 0;
	constexpr int CollInquiryStatus_ACCEPTED_WITH_WARNINGS = 1;
	constexpr int CollInquiryStatus_COMPLETED = 2;
	constexpr int CollInquiryStatus_COMPLETED_WITH_WARNINGS = 3;
	constexpr int CollInquiryStatus_REJECTED = 4;
	constexpr int CollInquiryResult_SUCCESSFUL = 0;
	constexpr int CollInquiryResult_INVALID_OR_UNKNOWN_INSTRUMENT = 1;
	constexpr int CollInquiryResult_INVALID_OR_UNKNOWN_COLLATERAL_TYPE = 2;
	constexpr int CollInquiryResult_INVALID_PARTIES = 3;
	constexpr int CollInquiryResult_INVALID_TRANSPORT_TYPE_REQUESTED = 4;
	constexpr int CollInquiryResult_INVALID_DESTINATION_REQUESTED = 5;
	constexpr int CollInquiryResult_NO_COLLATERAL_FOUND_FOR_THE_TRADE_SPECIFIED = 6;
	constexpr int CollInquiryResult_NO_COLLATERAL_FOUND_FOR_THE_ORDER_SPECIFIED = 7;
	constexpr int CollInquiryResult_COLLATERAL_INQUIRY_TYPE_NOT_SUPPORTED = 8;
	constexpr int CollInquiryResult_UNAUTHORIZED_FOR_COLLATERAL_INQUIRY = 9;
	constexpr int CollInquiryResult_OTHER = 99;
	constexpr char MDEntryMakerSide_BUY = '1';
	constexpr char MDEntryMakerSide_SELL = '2';
};